### PR TITLE
Improve EDNS handling

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

This PR merges a few EDNS related changes:

- **Add downstream EDE info for synthesized replies**
  This commit enriches downstream DNS replies with blocking information. This can be controlled (and also disabled) via the new setting `dns.blocking.edns`.
  Example:
  image

- **Add EDE 15 from upstream => Blocked detection**
  Pi-hole already detects NXRA (NXDOMAIN without RA bit from Quad9 or `unbound` with option [`rpz-signal-nxdomain-ra`](https://github.com/NLnetLabs/unbound/commit/392c1f0f5495cb0cc1170e126945caa7e988f47d)), NULL address (`0.0.0.0` / `::`) and a set of known IP addresses (Cisco Umbrella) to determine a query was blocked upstream. This PR adds a new detection that is a query has `EDE 15 = Blocked` set by the upstream resolver. This can be seen, e.g. in [routeDNS](https://github.com/folbricht/routedns/blob/53e9ecff2249082e6d901226faa93af2d9974e9c/doc/configuration.md?plain=1#L633) which is used by the user requesting this feature.

- **Unify query and cache status enums**
  This is mostly a code maintenance commit without any externally visible changes. It removes the `enum domain_client_status` in favor of the more generic `enum query_status`.

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** https://github.com/pi-hole/docs/pull/1094

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
Do we need amendments to the docs for the new database query status `QUERY_EXTERNAL_BLOCKED_EDE15`?

**Comment by DL6ER** [comment]
See https://github.com/pi-hole/docs/pull/1094

**Comment by rdwebdesign** [comment]
Do we need to change the web interface to show this new value?

**Review by yubiuser — APPROVED** [review]

**Comment by DL6ER** [comment]
@rdwebdesign No, in v6, we query FTL for the defined types and, hence, no web code changes are necessary if new types are added.

**Comment by rdwebdesign** [comment]
> no web code changes are necessary if new types are added.

Cool!

**Pull request merged**
