### PR TITLE
Upgrade RegEx engine

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

See extensive description here: https://discourse.pi-hole.net/t/regex-engine-improvements/34751
This does not change any dependencies.

### CODE REVIEW

**Comment by DL6ER** [comment]
So much for CodeFactor...

Screenshot at 2020-07-08 21-28-24

**Comment by DL6ER** [comment]
Rebased on latest `development`, ready for review + merge!

**Comment by dschaper** [comment]
MC on `src/datastructure.h`.

**Comment by DL6ER** [comment]
Merge conflict resolved

**Pull request merged**
