### PR TITLE
Remove gray color in help output

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

PR https://github.com/pi-hole/FTL/pull/1501 added a colorful output for `pihole-FTL -h`. 
For some items it uses a `gray` color - but this is hardly readable when the terminal background is not pitch black. 
 
Screenshot at 2023-01-08 22-18-44

This PR removed the `gray` and switches colors of those items to `purple`

Screenshot at 2023-01-08 22-25-59

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by dschaper** [comment]
I have no opinion on this PR directly but in general grey is fine to use, the visibility depends on your terminal color scheme.

**Comment by yubiuser** [comment]
Sure it depends on the terminal's color scheme. I did not modify this, this is the standard Linux Mint terminal with default settings.

**Comment by rdwebdesign** [comment]
Accessing via Putty (using default colors), the background is completely black, but the "normal white" is gray. 
Only bold white text is really white.

The **gray** parameter (`-q`) looks too dark:

image

**Review by DL6ER — APPROVED** [review]
I agree on (a) that color schemas are subjective and user-configurable, however, also on (b) that it should look reasonable on default palettes. As both, Putty and Linux Mint can be considered widespread, this change seems to be a good one.

And @yubiuser made sure we do not use it again by deleting the definition of gray altogether :+1:

**Pull request merged**
