### PR TITLE
Ensure each regex is imported only once

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Fixes a bug brought up on [Discourse](https://discourse.pi-hole.net/t/groups-and-regex/27732).

### CODE REVIEW

**Comment by dschaper** [comment]
Bugfinder confirms fix is working. https://discourse.pi-hole.net/t/groups-and-regex/27732/43

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/groups-and-regex/27732/44

**Comment by dschaper** [comment]
@DL6ER We need to revert this as it's causing crashes for users.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/ftl-crashes-while-using-the-web-interface/28115/9

**Pull request merged**
