### PR TITLE
Allow defining clients by their MAC address

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

This PR teaches FTL how to use MAC addresses to automatically identify clients immediately connected you the Pi-hole. This will make the configuration for clients changing their addresses frequently (non-deterministic DHCP server, IPv6 privacy extension, non-constant ISP IPv6 prefixes, etc.) easier than before.

Defining clients by IP addresses (possibly an entire subnet with CIDR notation) stays intact.

It works the following way: If we didn't find an IP address match (either exact or subnet), we lookup the IP address within the Network overview table. If we find a (sufficiently recent) IP address match there, we extract the corresponding MAC address. We use this MAC address for a new lookup in the `client` database table to see if there is a client configured with this MAC address.

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/groups-and-dhcp/31901/11

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/why-queries-table-doesnt-have-mac-address-column/33185/4

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/subnetting-is-not-working-with-most-relevant-entry/31482/29

**Comment by DL6ER** [comment]
Not attempting a rebase on this massive PR. An ordinary merge commit has to suffice here or I will be busy all night....

**Comment by DL6ER** [comment]
These changes seem to be stable. Several users are testing it on Discourse and nothing odd is being reported. I think it should go into `development` now to ease further FTL development as this PR touched a lot of files which make competing PRs difficult to do without introducing merge conflicts.

**Comment by yubiuser** [comment]
Can you please check the checksum of the latest build before merging this PR? I could not update due to checksum errors, see here: https://discourse.pi-hole.net/t/feedback-for-allow-defining-clients-by-their-mac-address-host-name-and-networking-interface/32324/191

**Comment by DL6ER** [comment]
@yubiuser I restarted the entire CI chain to rebuild the binaries. Please try again.

**Comment by yubiuser** [comment]
Worked, thanks.

**Comment by DL6ER** [comment]
Investigating possible 32 bit test hiccups.

**Comment by DL6ER** [comment]
The issue lies outside of Pi-hole:
```
connection timed out; no servers could be reached
```
caused some of the tests to fail.

I reran the test a few times and it did now pass each time.

**Pull request merged**
