### PR TITLE
Switch SSH deploy action

### PR DESCRIPTION
**Pull request by yubiuser**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** _{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar} 10

---

Switch from https://github.com/shimataro/ssh-key-action to https://github.com/benoitchantre/setup-ssh-authentication-action

Reason: the current action uses `Node.js 12` which is not supported by GH anymore, makes the deploy workflow failing. Also, the action repo looks a bit abandoned, last release 1 year ago with some open issues and pull requests. One issue is about Nodejs (https://github.com/shimataro/ssh-key-action/issues/207) where the author of the new action introduced it. 
The new action is much simpler and uses a pure `bash` approach making it less error-prone.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
The new action is only 3 days old. We'll see how it evolves. Still better than a stale action where development was discontinued.

**Review by DL6ER — COMMENTED** [review]
Are all the unrelated style changes intended?

**Comment by yubiuser** [comment]
`unrelated` vs. `intended` ;-)

No. My `vscode` formats `yml` files automatically since I enabled `Format on save` to allow `black` to format `py` files on save.

Do you want me to revert this?

**Comment by DL6ER** [comment]
Yes, I guess some other editor formatted it the way it is right now and this adds a lot of noise to the diffs. I have auto-format disabled all the time and only do it for projects where a common style is *enforced*. But this is still work in progress over here...

**Comment by yubiuser** [comment]
FP on request

**Review by DL6ER — APPROVED** [review]

**Pull request merged**
