### PR TITLE
Make REPLY_WHEN_BUSY=DROP the new default (was ALLOW)

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

The current default is in conflict with the description in https://github.com/pi-hole/FTL/pull/1156 which says we use `DROP` as the default. This is changed here.

### CODE REVIEW

**Comment by dschaper** [comment]
If the database is locked because of a broken install will this change mean all replies are dropped? (And badly behaving clients then slam the hell out of FTL with retries?)

Not that we can do much about bad clients but would like to know for troubleshooting purposes if we see retry floods.

**Review by yubiuser — APPROVED** [review]

**Comment by DL6ER** [comment]
@dschaper You are right. Maybe this is the argument *against* this change? And maybe even why it is like it is right now.

**Comment by dschaper** [comment]
I agree with the change, my only concern is how to handle the queries in that situation. I think a rejection or SRVERR if possible?

**Comment by yubiuser** [comment]
I think this is a target conflict: we can not set the default to drop to preserve privacy when the database is busy and at the same time prevent dropping all queries in case we do have a database malfunction. 
If DB is busy all the time and users loose internet connection they certainly will ask for help. In their `pihole-FTL.log` will be hundreds of `REPLY_WHEN_BUSY: Drop queries when the database is busy` which should give us a good troubleshooting guidance what the culprit is.

**Comment by DL6ER** [comment]
> hundreds of `REPLY_WHEN_BUSY:` [...]

Yeah, until the SD card is full (can definitely happen in less than a day). Also, we don't know if they can even ask for help without working DNS.

Something tells me this solution here is too simple and will cause too many issues - only for very few users but they'll be affected heavily.

Say we could reliability tell apart a busy database from a broken one, what should we do? Allow on broken and drop on busy? What is a third party script is keeping the database busy all the time (okay, this may go too far)?

**Comment by yubiuser** [comment]
On the other hand: if the database is broken or a script is keeping the database busy, dropping the queries (and thereby blocking DNS) will signal "something is wrong" to the user. If we just allow the queries, the might never notice...

**Comment by DL6ER** [comment]
After having slept on it for a few nights, I tend to agree on this change. Yes, a few users will notice an issue with their database, this taking down DNS resolution and will will come here and complain, possibly loudly. In the end that seems acceptable for the benefit of ensuring that database issues will not cause the Pi-hole to stop filtering.

We will make it very clear in the upcoming release notes that the default value changes here and everyone wanting to preserve the current behavior can easily do this be explicitly adding the setting `REPLY_WHEN_BUSY=ALLOW` to the config file.

**Comment by dschaper** [comment]
SGTM

**Pull request merged**
