### PR TITLE
[WIP] Update README.md

### PR DESCRIPTION
**Pull request by WaLLy3K**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:**

0

---

* Make readme match the style and formatting of Core
* Add Rock64 to compatibility list

### CODE REVIEW

**Comment by DL6ER** [comment]
@WaLLy3K Is this in a mergeable state (i.e. in sync with your work for `core` and `web`)?

**Comment by WaLLy3K** [comment]
No it isn't, sorry. I can't add the WIP tag, so I'll edit the title.

**Comment by DL6ER** [comment]
The `WIP` label did not exist for this repo. I just created it an will add it to this PR in addition.

**Comment by DL6ER** [comment]
@WaLLy3K I'll close this PR for now. The readme needs a bit of love anyways when we merge *FTL*DNS™ later on. Feel free to re-open and work on this whenever you like.

**Pull request closed without merging**
