### PR TITLE
I would like to request mipsel binaries

### PR DESCRIPTION
**Pull request by Katana-Steel**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [] I have considered, and confirmed that this submission will be valuable to others.
- [] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** _{replace this text with a number from 1 to 10, with 1 being not familiar, and 10 being very familiar}_

---

_{replace this line with your pull request content}_

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by dschaper** [comment]
Please open a Feature Request at https://discourse.pi-hole.net. Editing the README is not the way to request new platform support, it is a list of platforms tested and known to work.

**Comment by DL6ER** [comment]
Furthermore, you ignored the entire template. Especially the part

> Please submit all pull requests against **the development branch**. Failure to do so will delay or deny your request

We don't have this table anymore in our README as the compatibility list and much else has moved to https://docs.pi-hole.net

**Comment by Mcat12** [comment]
The wording can be improved, but that line is not for adding architectures, only for showing that you have tested a build on a board or distro. For example, if a new SBC comes out that uses armhf and you tested it on that board, you could add it, but not if you want a new architecture.

**Comment by DL6ER** [comment]
> that read to me like open a PR for the README?

Yes, but the section I quoted says:

> **submit all pull requests against the development branch**

Furthermore, if you check the [README of the `development` branch](https://github.com/pi-hole/FTL/blob/development/README.md) you can see that the table is gone, hence there is nothing you could add your line to...

**Pull request closed without merging**
