### PR TITLE
Tweak API history endpoint and fix cached counting

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Two improvements for the main activity, and one bug fix for the clients activity graphs API endpoints:

- Include forwarded queries in `/api/history`
- Count stale-cache queries as cached queries in `/api/history`
- Fix duplicated clients in `/api/history/clients`

> [!NOTE]
> Needs https://github.com/pi-hole/web/pull/2956 to be checked out

---

**Related issue or feature (if applicable):** https://discourse.pi-hole.net/t/dashboard-graphs-dont-match/68263

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by DL6ER** [comment]
Has been confirmed working on the related Discourse thread

**Comment by sawsanders** [comment]
While the initial double counting is fixed, I noticed that the client graphs show clients with zero queries in some time periods while still having many queries reported in the "other" category. I only saw this after I set the number of max clients back to 10 from 100.

Screenshot 2024-02-15 at 8 11 27 PM


IMHO, it shouldn't show zero query clients when it has clients in the "other" category to use instead.

**Comment by DL6ER** [comment]
The problem we are facing here is limited number of distinct (and also distinguishable as in "by humans") colors. If we'd starting showing different clients the way your suggest (which is surely meaningful in some way), we'd quickly reach 20 or more colors even if the limit is set to 10 - or even less.

It would mean that the color palette starts repeating at some point and - in my personal opinion - if the red client is the printer in the morning, and then some random smart home devices the rest of the day, this would possibly cause much more confusion that it'd be useful in the end.

What do you think?

**Comment by sawsanders** [comment]
> The problem we are facing here is limited number of distinct (and also distinguishable as in "by humans") colors. If we'd starting showing different clients the way your suggest (which is surely meaningful in some way), we'd quickly reach 20 or more colors even if the limit is set to 10 - or even less.
> 
> It would mean that the color palette starts repeating at some point and - in my personal opinion - if the red client is the printer in the morning, and then some random smart home devices the rest of the day, this would possibly cause much more confusion that it'd be useful in the end.
> 
> What do you think?

I see your point and it all really comes down to a matter of preference.

I'd rather see the true top 10 (or whatever is configured) when I hover over the bars; it allows me a quick glance on client activity over that period. Sometimes the "others" category squishes down the lower frequency ones, making them hard to discern the colors.

You (and others I'm sure) feel that consistent colors are the way to go. That's fine too and I'm ok with it. It's hard to make everyone happy.

**Comment by sawsanders** [comment]
Wow. That was not expected, but thank you and I’ll do my best to put this through its paces.

**Comment by DL6ER** [comment]
> now it’s almost painfully slow

It is dependent on mainly two factors (1) the device your browsers runs on and (2) the number of clients shown *in total*.

While (1) is obviously always the same and much worse on a phone than, e.g., on a modern laptop, (2) is strongly influences by the setting being either `true` (maximum 10 clients) or `false` (possibly hundreds).

There is nothing we could really do about it, it's Javascript driven and only UI-side.

**Comment by sawsanders** [comment]
I noticed a one time mis-sorting of the "Top Permitted Domains" section of the dashboard.

There was one domain with 2 hits in third place on the list while the rest of the top 10 had over 1000. I went to make a screen shot, messed up, reloaded the page and the problem dissapeared after the page reloaded.

I will try to get a screen shot or other information if/when I see it again.

**Comment by DL6ER** [comment]
@sawsanders Thanks! Fixed with the last commit.

**Comment by sawsanders** [comment]
18 hours and counting. Everything working as expected.

**Comment by sawsanders** [comment]
Everything is still working as expected. I feel confident that the issue is solved with this PR. 

Thank you!

**Comment by Gontier-Julien** [comment]
Tested it and it working as expected too after a 4 days 👍🏻

**Review by PromoFaux — DISMISSED** [review]
Happy to approve based on testing users comments.

**Comment by DL6ER** [comment]
Waiting for https://github.com/pi-hole/web/pull/2956 to be approved before merging this one

**Review by PromoFaux — APPROVED** [review]
re-reviewing based on testing users comments

**Pull request merged**
