### PR TITLE
Update Error Message Referring to "Adlist"

### PR DESCRIPTION
**Pull request by NittanySeaLion**
## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---
The web interface now refers to Adlists as List. This change updates the FTL code database warning to refer to "List" instead of "Adlist." 

No changes were made to the database table itself -- it still refers to "adlist" variable, which may be an area for a future update better made by a database person.

**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Review by yubiuser — APPROVED** [review]

**Review by DL6ER — APPROVED** [review]

**Comment by DL6ER** [comment]
@NittanySeaLion

> The base branch requires all commits to be signed. [Learn more about signing commits.](https://docs.github.com/articles/about-gpg/)

You can either use a [GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#gpg-commit-signature-verification) (preferred method) or an [SSH key](https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification#ssh-commit-signature-verification) to generate the signatures. It is a one-time setup and will ensure you can sign all commits also in the future.

**Comment by NittanySeaLion** [comment]
@DL6ER 

I followed the instructions and am not sure why the GPG key isn't applied. Also, I don't remember whether I made the offending commit using Android Studio or using Github browser. Does that make a difference? 

In any event, I've rechecked the Android Studio settings, and it was supposed to do the right thing. Should I be using something else to edit?

I'll try to keep an eye on the "Verified," which is what I think you're looking for. Apologies for the trouble.

**Comment by DL6ER** [comment]
Your commit above is not signed. You will need to re-commit it, e.g., with `git commit -S --amend` and then `git push -f` to force an update of your branch with the now signed commit.

**Comment by NittanySeaLion** [comment]
Thanks. I used Visual Studio, and it looks like it applied the key. Let me know if anything else is needed.

**Comment by DL6ER** [comment]
That's it. Thanks!

**Pull request merged**
