### PR TITLE
Enable history and auto-completion for embedded SQLite3 engine

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

See title. Everything was already configured correctly, we just needed to enable the feature. For the sake of simplicity, we use the history of `sqlite3` so you can immediately use `pihole-FTL sql` with your recent history. Auto-completion is available though <kbd>Tab</kbd>, as usual.

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
> Add -DHAVE_READLINE and the -lreadline and -lncurses libraries to get command-line editing support.

https://www.sqlite.org/howtocompile.html

Do we have those "-lreadline and -lncurses libraries" inclueded?

**Comment by DL6ER** [comment]
Yes, `ncurses` isn't needed, `readline` is added here:
https://github.com/pi-hole/FTL/blob/7387e81981760c835148b7f5f61302b91ee83e7d/src/CMakeLists.txt#L206-L213

**Review by yubiuser — APPROVED** [review]
Approving. Please wait for feedback from discourse before merging.

**Review by dschaper — APPROVED** [review]

**Comment by yubiuser** [comment]
Reported to be working on discourse:
https://discourse.pi-hole.net/t/sqlite3-autocomplete/52530/4?u=yubiuser

**Pull request merged**
