### PR TITLE
Simplify/fix redirection rules

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

The PR has two connected goals:

1. Simplify redirection rules.
   Before we had an explicit rule to redirect rules ending in slashes to strip the slash, e.g. `pi.hole/admin/` to `pi.hole/admin`. However, as both URLs will work equally well, there is no need for this redirection.
2. When directly trying to access a directory, CivetWeb tries to determine the server hostname so it can send an **absolute** redirect (301). Especially when being behind a proxy, this will always fail and cause dead-end redirections.
   We solve this by patching CivetWeb to use **relative** redirections instead. This fully resolves this issue. The patch is added to our existing series of patches to ensure it can be re-applied in future CivetWeb upgrades.
   You can try this with, e.g. http://pi.hole/admin/scripts/ - the expected outcome is:
   ```
   Error 403: Forbidden
   Error: Directory listing denied
   ```
   The bug is: Redirection to *somewhere* (may be the IPv4 or IPv6 address of your Pi-hole).

As you can guess, these two were even able to play some weird ping-pong sending users with non-default deployments into the wild.

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
4. I have commented my proposed changes within the code.
5. I am willing to help maintain this change if there are issues with it later.
6. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
7. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
Should such an access error be logged to `/var/log/pihole/webserver.log`? So far, it isn't.

**Comment by yubiuser** [comment]
Is it expected to get redirects from `hostname/admin/scripts/` to `IP/admin/script` (where the error message is shown)?

**Comment by DL6ER** [comment]
> Is it expected to get redirects from hostname/admin/scripts/ to IP/admin/script (where the error message is shown)?

No, actually the opposite should be true (redirecting `script` -> `script/`). Please try in a private browser window so we can exclude the redirect comes from cache (it happened to me quite a lot which was really confusing at first).

**Review by yubiuser — APPROVED** [review]
It was a browser cache issue. All good.

**Pull request merged**
