### PR TITLE
Fix spell checker action

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Fixes the spell checker action by adding a few unknown words to the ignore dictionary. Can be verified locally using
```
act -j spell-check
```

### CODE REVIEW

**Review by yubiuser — DISMISSED** [review]
(Re)move the already existing file?

https://github.com/pi-hole/FTL/blob/master/.codespellignore

**Comment by DL6ER** [comment]
For whatever reason, I really did not see this file... Force-pushed away. Having it inside `.github` seems cleaner compared to cluttering the root dir. In the end it is not part of FTL but meant for the CI.

**Review by yubiuser — COMMENTED** [review]
@PromoFaux was implementing this at the beginning. I think he discovered an issue with `spellcheck` where the ignorelist ignored items unless they were written all lower-case. I don't know if something changed on their side, but to be safe I would go for all lower-case. (which removes the duplicate `EDE/ede`) as well.

**Comment by DL6ER** [comment]
Done

**Pull request merged**
