### PR TITLE
Add HTTP/2 support

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Add HTTP/2 support to `civetweb`

**How does this PR accomplish the above?:**

**Link documentation PRs if any are needed to support this PR:**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by DL6ER** [comment]
Thank you for working on this! However, I converted this to draft mode as it isn't ready for merging. It is *somewhat* working but not really, e.g., following test:

```
$ curl -vs --http2 --cacert /etc/pihole/tls.crt --cert /etc/pihole/tls.pem https://pi.hole/admin/login -o/dev/null -w '%{http_version}\n
'
* Host pi.hole:443 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:443...
* Connected to pi.hole (::1) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/pihole/tls.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [497 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [111 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=pi.hole
*  start date: Jan 17 09:56:31 2024 GMT
*  expire date: Jan 17 09:56:31 2054 GMT
*  subjectAltName: host "pi.hole" matched cert's "pi.hole"
*  issuer: CN=pi.hole; O=Pi-hole; C=DE
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA256
} [5 bytes data]
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://pi.hole/admin/login
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: pi.hole]
* [HTTP/2] [1] [:path: /admin/login]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
} [5 bytes data]
> GET /admin/login HTTP/2
> Host: pi.hole
> User-Agent: curl/8.5.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
* HTTP/2 stream 1 was not closed cleanly: HTTP_1_1_REQUIRED (err 13)
} [5 bytes data]
* Downgrades to HTTP/1.1
* Empty reply from server
* Connection #0 to host pi.hole left intact
* Issue another request to this URL: 'https://pi.hole/admin/login'
* Found bundle for host: 0x571440da60c0 [can multiplex]
* Hostname pi.hole was found in DNS cache
*   Trying [::1]:443...
* Connected to pi.hole (::1) port 443
* ALPN: curl offers http/1.1
* SSL reusing session ID
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [622 bytes data]
*  CAfile: /etc/pihole/tls.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [128 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [25 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / UNDEF
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=pi.hole
*  start date: Jan 17 09:56:31 2024 GMT
*  expire date: Jan 17 09:56:31 2054 GMT
*  subjectAltName: host "pi.hole" matched cert's "pi.hole"
*  issuer: CN=pi.hole; O=Pi-hole; C=DE
*  SSL certificate verify ok.
* using HTTP/1.x
} [5 bytes data]
> GET /admin/login HTTP/1.1
> Host: pi.hole
> User-Agent: curl/8.5.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/1.1 200 OK
{ [5 bytes data]
< Cache-Control: no-cache, no-store, must-revalidate, private, max-age=0
{ [5 bytes data]
< Expires: 0
{ [5 bytes data]
< Pragma: no-cache
{ [5 bytes data]
< Content-Security-Policy: default-src 'self' 'unsafe-inline';
{ [5 bytes data]
< X-Frame-Options: DENY
{ [5 bytes data]
< X-XSS-Protection: 0
{ [5 bytes data]
< X-Content-Type-Options: nosniff
{ [5 bytes data]
< Referrer-Policy: strict-origin-when-cross-origin
{ [5 bytes data]
< Access-Control-Allow-Headers: *
{ [5 bytes data]
< Access-Control-Allow-Methods: *
{ [5 bytes data]
< Content-Type: text/html; charset=utf-8
{ [5 bytes data]
< Date: Sun, 10 Nov 2024 09:05:04 GMT
{ [5 bytes data]
< Connection: close
{ [5 bytes data]
< 
{ [5 bytes data]
* TLSv1.3 (IN), TLS alert, close notify (256):
{ [2 bytes data]
* Closing connection
} [5 bytes data]
* TLSv1.3 (OUT), TLS alert, close notify (256):
} [2 bytes data]
1.1
```

Emphasis on:
> `* HTTP/2 stream 1 was not closed cleanly: HTTP_1_1_REQUIRED (err 13)`

Looking at https://github.com/civetweb/civetweb/issues/875#issuecomment-633673720, we see:

> respond to **HTTP/2 requests to user callbacks** with a "**this endpoint (URL) supports HTTP/1.1 only (HTTP_1_1_REQUIRED)**". CivetWeb will only serve static files (HTML, JS, CSS, images, ...). This is a valid response. Firefox/Chrome/Edge will retry using HTTP/1.1, curl will return an error with code 'HTTP_1_1_REQUIRED (13)' even if -L (follow redirects) is set.

which indeed seems to be the case, e.g., https://pi.hole/admin/img/logo.svg:
```
curl -vs --http2 --cacert /etc/pihole/tls.crt --cert /etc/pihole/tls.pem https://pi.hole/admin/img/logo.svg -o/dev/null -w '%{http_version}\n'
* Host pi.hole:443 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:443...
* Connected to pi.hole (::1) port 443
* ALPN: curl offers h2,http/1.1
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
*  CAfile: /etc/pihole/tls.crt
*  CApath: /etc/ssl/certs
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [497 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [110 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / X25519 / id-ecPublicKey
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=pi.hole
*  start date: Jan 17 09:56:31 2024 GMT
*  expire date: Jan 17 09:56:31 2054 GMT
*  subjectAltName: host "pi.hole" matched cert's "pi.hole"
*  issuer: CN=pi.hole; O=Pi-hole; C=DE
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using ecdsa-with-SHA256
} [5 bytes data]
* using HTTP/2
* [HTTP/2] [1] OPENED stream for https://pi.hole/admin/img/logo.svg
* [HTTP/2] [1] [:method: GET]
* [HTTP/2] [1] [:scheme: https]
* [HTTP/2] [1] [:authority: pi.hole]
* [HTTP/2] [1] [:path: /admin/img/logo.svg]
* [HTTP/2] [1] [user-agent: curl/8.5.0]
* [HTTP/2] [1] [accept: */*]
} [5 bytes data]
> GET /admin/img/logo.svg HTTP/2
> Host: pi.hole
> User-Agent: curl/8.5.0
> Accept: */*
> 
{ [5 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
{ [265 bytes data]
* old SSL session ID is stale, removing
{ [5 bytes data]
< HTTP/2 200 
< cache-control: max-age=3600
< content-security-policy: default-src 'self' 'unsafe-inline';
< x-frame-options: DENY
< x-xss-protection: 0
< x-content-type-options: nosniff
< referrer-policy: strict-origin-when-cross-origin
< access-control-allow-headers: *
< access-control-allow-methods: *
< content-type: image/svg+xml
< last-modified: Wed, 05 Oct 2022 02:37:57 GMT
< etag: "633cee05.986"
< content-length: 986
< accept-ranges: bytes
< date: Sun, 10 Nov 2024 09:25:20 GMT
< 
{ [986 bytes data]
* Connection #0 to host pi.hole left intact
2
```
Note: I had to temporarily remove some the `request_handler` in `webserver.c` for this. This handler takes care of notifying the user where the API is, redirecting unauthorized requests to `/admin/login`, ... so something we still need.

This is not very good...

**Comment by DL6ER** [comment]
I did just discover another issue. Our CI API validation fails because [Python's `requests`](https://docs.python-requests.org/en/latest/) does not support HTTP/2 and, apparently, HTTP/1.1 doesn't work in the legacy mode (as it should) with `civetweb` having `enable_http2 = yes`.

**Comment by yubiuser** [comment]
https://www.python-httpx.org/quickstart/ could be used on the CI to send 1.1/2 requests.

**Comment by yubiuser** [comment]
We agreed to put this on hold for now. `civetweb`might not be the right web server for http/2 support as it requires to many changes and adoption. We can revise this in the future with a different web server in the backend or a http/2 proxy in front.
Suggestions are welcomed.

**Comment by yubiuser** [comment]
I'm going to close the PR, but will keep the branch. Maybe it can be beneficial in the future.

**Pull request closed without merging**
