### PR TITLE
Add powerpc arch

### PR DESCRIPTION
**Pull request by mterron**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 1

---

Add powerpc arch to the build scripts.

### CODE REVIEW

**Comment by DL6ER** [comment]
Fixes #71

**Comment by mterron** [comment]
Just an observation. The generated binary is significantly larger than the one I got from compiling on GCC 4.9.2. Seem to work alright AFAIK.

```bash
root@MyBook-Live:~# file pihole-FTL-powerpc-linux-gnu $(which pihole-FTL)
pihole-FTL-powerpc-linux-gnu: ELF 32-bit MSB shared object, PowerPC or cisco 4500, version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 2.6.32, BuildID[sha1]=98a2b550f82ca20d8580ba3c9c0585802a9c0db0, not stripped
/usr/bin/pihole-FTL:          ELF 32-bit MSB shared object, PowerPC or cisco 4500, version 1 (SYSV), dynamically linked, interpreter /lib/ld.so.1, for GNU/Linux 2.6.32, BuildID[sha1]=684983a82263186ef118bea6e1c9738fa8b9b87b, not stripped
root@MyBook-Live:~# ls -lh pihole-FTL-powerpc-linux-gnu $(which pihole-FTL)
-rwxr-xr-x 1 root root 1.4M Jun 20 07:24 pihole-FTL-powerpc-linux-gnu
-rwxr-xr-x 1 root root 383K Jun 14 16:45 /usr/bin/pihole-FTL
root@MyBook-Live:~# gcc --version
gcc (Debian 4.9.2-10) 4.9.2
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by dschaper** [comment]
May be from the debugging symbols that we leave in the binary for `gdb` to be able to assist with any issues.

@DL6ER Am I vastly incorrect?

**Comment by mterron** [comment]
Ignore that, compiling the same version gives similar results. Seems that between pihole-FTL v2.8.2 and v2.9.2 the filesize grew from ~400kb to ~1.4MB.

**Pull request merged**
