### PR TITLE
Simple maintenance improvements

### PR DESCRIPTION
**Pull request by a1346054**
**By submitting this pull request, I confirm the following:**

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 4

Contains whitespace fixes that make some editors deal with the content better.

### CODE REVIEW

**Review by yubiuser — DISMISSED** [review]

**Comment by DL6ER** [comment]
> make some editors deal with the content better

Can you elaborate on this? Just for the purpose of personal education.

**Comment by a1346054** [comment]
> > make some editors deal with the content better
> 
> Can you elaborate on this? Just for the purpose of personal education.

Some (arguably badly-behaving, though standards respecting) editors will not display the final line if it is not terminated by a newline, due to it not being posix compliant.

Other breakage I've seen is editors wrapping text at wrong points because they consider trailing whitespace to be part of the last word.

**Review by DL6ER — DISMISSED** [review]

**Comment by DL6ER** [comment]
Do you want to [sign your commits](https://docs.github.com/articles/about-gpg/)? Otherwise, I can overwrite the repository-wide role to only accept GPG signed commits.

**Comment by a1346054** [comment]
Thanks for the tip, I'll look into that (it was on my todo list anyway to investigate gpg signing commits). In the meantime, feel free to do whatever you wish with this PR, commit it in your own name without attribution if that helps, I really don't mind.

**Comment by DL6ER** [comment]
We're neither in a rush nor is this fixing any security related stuff. Hence, we have the time to wait until you are ready. Take your time.

**Comment by a1346054** [comment]
I've done some testing and came up with an interesting question that I don't know the answer to.

1) create a gpg key
1) put it into github
1) use it to sign commits
1) observe the commit shows verified
1) remove the gpg key from github
1) observe the previously verified commit shows as unverified

Would it therefore cause any issues for pi-hole/FTL if I removed the gpg key at some point in the future, and my commits would show up as unverified?

**Comment by DL6ER** [comment]
No, not if your commits already hit `master`.

But why would you delete the key from GitHub? If you are worried about loosing it (because of a data catastrophe) you can do either:

1. Limit the validity of the key to, say, one year, or
2. Have an unlimited key and store it (password encrypted!) in several safe, physically separated locations. Including at least one "offline" version, i.e., a printed out version on paper you'd OCR of everything failed (storage device age).

**Comment by a1346054** [comment]
I gpg-signed the commits now. Thank you for bringing this to my attention, I learned a lot.

**Review by DL6ER — APPROVED** [review]

**Pull request merged**
