### PR TITLE
Group dependabot PRs

### PR DESCRIPTION
**Pull request by yubiuser**
**What does this PR aim to accomplish?:**

Recently, Github added the feature of combining multiple Dependabot PRs into one. This PR will combine all Dependabot PRs into a single PR

https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by yubiuser** [comment]
The codespell errors are fixed in`development-v6` already.

**Comment by PromoFaux** [comment]
This will need updating, I think, to include the additional changes in `dependabot.yml` for the v6 branches

**Comment by PromoFaux** [comment]
Rebased on development (after merging the master->dev sync) to account for v6 dependabot settings

**Review by DL6ER — APPROVED** [review]

**Comment by yubiuser** [comment]
I can't merge this.

**Pull request merged**
