### PR TITLE
Fix DELETE API endpoints return codes

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

The `DELETE` endpoints should return 204 when something was deleted and 404 is nothing was found at this resource. This PR follows a discussion in #1833 

See here the result of triggering to identical `DELETE` for a blocked domain. The first one got deleted fine (204), the second one errored because the requested resource wasn't there (we delete it before):

Screenshot from 2023-12-21 21-09-31

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
Documentation suggest there is an empty response for a `404`, however, it responds with the time it took.

```
chrko@ThinkPad-X230:~$ curl -s -k -w "%{http_code}" -X DELETE "https://nanopi.lan/api/domains/deny/exact/erewr" --data '{"sid":"rOtDZXJOO9oJ+jtIiKE67w="}' | jq .
{
  "took": 0.00680232048034668
}
404
```

**Comment by yubiuser** [comment]
Should this be extended to `/info/messages/{message_id}`, `/network/devices/{device_id}` (both missing 404 and one 401 and one 400), and `/config/{element}/{value}` and `/dhcp/leases/{ip}`.

How does it work for the `batchDelete` endpoints - e.g. only one item of the array is not found?

**Comment by DL6ER** [comment]
> How does it work for the batchDelete endpoints - e.g. only one item of the array is not found?

Domains to be removed are added into the temporary table `deltable`, we thereafter run something like
``` sql
DELETE FROM domainlist WHERE domain IN (SELECT item FROM deltable);
```
hence, deleting domains that do not exist is harmless. FTL reacts with `204 Gone` when at least one item has been deleted, otherwise - when no item was deleted, FTL returns `404 Not Found`.

This also means that if you want to delete `["a.com","b.com","c.com"]` but none of them exist in your lists, you will get a `404`. If at least one of them exist, you get `204`.

**Comment by DL6ER** [comment]
I rebased this branch on latest `development-v6`.

> Documentation suggest there is an empty response for a 404, however, it responds with the time it took.

Thanks. I should have added `took` to all 404 where they are sent now, I also changed to code to never include them when we are sending `204` (as per standard).

> Should this be extended to /info/messages/{message_id}, /network/devices/{device_id} (both missing 404 and one 401 and one 400), and /config/{element}/{value} and /dhcp/leases/{ip}?

Yes and I did that. I did it in small chunks to ease reviewing.

**Comment by yubiuser** [comment]
Status 200 for `/auth` is not documented (no password set at all > nothing to delete)

```
curl -s -o /dev/null -w "%{http_code}" -X DELETE "http:/nanopi.lan/api/auth"  -H "Accept: application/json" -H "sid: null"
200
```

**Comment by yubiuser** [comment]
Something is wrong. The latest changes prevent setting an empty password at all.
```
2024-01-07 20:29:49.184 [469542/T469594] WARNING: Failed to create password hash (verification failed), password remains unchanged
2024-01-07 20:29:49.185 [469542/T469594] WARNING: API: Config item is invalid (webserver.api.password: Failed to create password hash (verification failed), password remains unchanged)
```

**Comment by DL6ER** [comment]
Ah yes, thanks for pointing this out. Now we found what was relying on the previous code that said "empty password is always correct"

**Pull request merged**
