### PR TITLE
 Implement selective Teleporter restoring

### LINKED ISSUE #1802: Selective teleporter restoration not possible.
Teleporter backups can only be restored entirely, but sometimes only some data needs to be restored. This is possible with v5, but not v6

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Add optional JSON object `.import` to `POST /api/teleporter` that allows the user to pick what is to be restored.
Fixes #1802

Screenshot

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by DL6ER** [comment]
I added the `Needs testing` label on this one because I have not tested any possible combination and also don't actually have a valid v5 `tar.gz` to test this changed code path.

**Comment by LizenzFass78851** [comment]
> I added the `Needs testing` label on this one because I have not tested any possible combination and also don't actually have a valid v5 `tar.gz` to test this changed code path.

Try using the teleporter file from pihole version 5 from @RPiList.
https://github.com/RPiList/specials/blob/master/TP-ohne-Banken-2023-12.tar.gz

**Comment by LizenzFass78851** [comment]
I tested this with the teleporter file mentioned in the last message and now the following result came as a response from the API:

Screenshot (105)

Seems as if the pihole api (in this case) did not read and/or transmit all files from the v5 teleporter file. Therefore, among other things, it did not restore the block lists from the teleporter file

---

I tested the same thing with a v6 teleporter file and got the following result:

Screenshot (106)

It worked with the v6 teleporter file (I can't say whether that's the case because it's the first teleporter file after setting up the pihole)

---

I tested it with the embedded pihole docs ui at http://localhost/api/docs/
I can't test it with postman or similar tools at the moment (maybe it's not as easy with postman as it is with the docs UI)

Here is the debug token: https://tricorder.pi-hole.net/wocT9uhL/
here is the [FTL.log](https://github.com/pi-hole/FTL/files/14223803/FTL.log)

**Comment by LizenzFass78851** [comment]
I'm sorry for the many comments, but I wanted to be helpful since this pr is tagged as "needs testing".

I tested further and I noticed that if I import a v5 teleporter file via the web UI as normal, it works perfectly:

Screenshot (107)

**But** if I do the same thing if I change the `ftl` to the branch of this pr then the same list of the imported files comes up as in the api docs ui:

Screenshot (108)

It may be that certain changes in this pr mean that it is no longer possible to import a v5 teleporter file correctly (since it does not import all files such as the file that saved the adlists).

(unless it was intentional).

**Comment by DL6ER** [comment]
I'm always thankful for more testing so feel free to go ahead 😉

It isn't intentional so that's probably some small logic error in the V5 part, I'll come back to you here when I had some more testing time

**Comment by DL6ER** [comment]
Sorry for the huge delay, I brought the branch back up to speed. @LizenzFass78851 If you are still in position where you could check this again, it'd be very helpful if you could retest and - if the files are still not imported - if any lines like
```
Skipping import of ... as it was not requested for import
```
are in `/var/log/pihole/FTL.log`

**Comment by LizenzFass78851** [comment]
I don't think I can test it now because the github workflow to create the binery failed 
https://github.com/pi-hole/FTL/actions/runs/8491942796/job/23264429941?pr=1874

**Comment by DL6ER** [comment]
Sorry, this was an unforeseen side-effect of #1919 but the CI tests have been right. I fixed this in the most recent commit.

**Comment by LizenzFass78851** [comment]
I counter-tested it again and the result is as follows:

While with the "ftl" branch development-v6 the teleporters can be successfully imported via the web UI (localhost/admin):

- v5 teleporter
Screenshot (6)


- v6 teleporter
Screenshot (7)


Then when I tried with the "ftl" branch of these pr, it still didn't work with the v5 teleporter (the output with the expected amount of imported files was not like the development v6 branch).

- v5 teleporter
Screenshot (9)


- v6 
Screenshot (8)
teleporter


the same under localhost/api/docs with "ftl" branch from these pr.

- v6 teleporter
Screenshot (11)

https://tricorder.pi-hole.net/rULKztoV/
[FTL.log](https://github.com/pi-hole/FTL/files/14812817/FTL.log)

**Comment by DL6ER** [comment]
Thanks, could you look up the lines ("Skipping import ...") in the log file `/var/log/pihole/FTL.log`? Unfortunately, the debug log contains only a very narrow excerpt from the log and those lines weren't among them.

**Comment by LizenzFass78851** [comment]
> Thanks, could you look up the lines ("Skipping import ...") in the log file `/var/log/pihole/FTL.log`? Unfortunately, the debug log contains only a very narrow excerpt from the log and those lines weren't among them.

Yes. entries actually exist:

```
cat /home/testu/FTL.log | grep "Skipping import"
2024-03-30 18:16:06.683 [34387/T34396] INFO: Skipping import of "adlist.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:16:06.683 [34387/T34396] INFO: Skipping import of "adlist_by_group.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:16:06.683 [34387/T34396] INFO: Skipping import of "blacklist.exact.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:16:06.683 [34387/T34396] INFO: Skipping import of "blacklist.regex.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:16:06.683 [34387/T34396] INFO: Skipping import of "client.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:16:06.684 [34387/T34396] INFO: Skipping import of "client_by_group.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:16:06.684 [34387/T34396] INFO: Skipping import of "domainlist_by_group.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:16:06.684 [34387/T34396] INFO: Skipping import of "group.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:16:06.684 [34387/T34396] INFO: Skipping import of "whitelist.exact.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:16:06.684 [34387/T34396] INFO: Skipping import of "whitelist.regex.json" as it was not requested for import (JSON: no, gravity: no)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "adlist.json" as it was not requested for import (JSON: yes, gravity: yes)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "adlist_by_group.json" as it was not requested for import (JSON: yes, gravity: yes)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "blacklist.exact.json" as it was not requested for import (JSON: yes, gravity: yes)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "blacklist.regex.json" as it was not requested for import (JSON: yes, gravity: yes)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "client.json" as it was not requested for import (JSON: yes, gravity: yes)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "client_by_group.json" as it was not requested for import (JSON: yes, gravity: yes)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "domainlist_by_group.json" as it was not requested for import (JSON: yes, gravity: yes)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "group.json" as it was not requested for import (JSON: yes, gravity: yes)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "whitelist.exact.json" as it was not requested for import (JSON: yes, gravity: yes)
2024-03-30 18:37:24.378 [35529/T35537] INFO: Skipping import of "whitelist.regex.json" as it was not requested for import (JSON: yes, gravity: yes)
```

**Comment by DL6ER** [comment]
Oh yes, I was right a long time ago ...

> that's probably some small logic error in the V5 part

Should be improved now :crossed_fingers:

**Comment by LizenzFass78851** [comment]
**it worked**

- on `localhost/admin`
  v5 teleporter
Screenshot (12)

- on `localhost/api/docs`
  v5 teleporter
Screenshot (13)

here is the complete [FTL.log](https://github.com/pi-hole/FTL/files/14813106/FTL.log)

**Comment by DL6ER** [comment]
@pi-hole/ftl-maintainers This PR should finally be ready. The good part of the long delay is that the implemented logix is even simpler than before and this branch currently being 100% up-to-date with `development-v6`. This makes unforeseen issues old PRs like to cause when being merged ~~impossible~~ really unlikely.

**Comment by PromoFaux** [comment]
> it worked

👍

**Review by PromoFaux — APPROVED** [review]

**Pull request merged**
