### PR TITLE
Handle pi.hole and hostname interface-dependent

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

This PR makes FTL automatically reply with the appropriate IP address to both `pi.hole` and the machine's hostname. The address FTL replies with can be overwritten using the `REPLY_ADDR4/6` settings.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Looks good, but there is a merge conflict

**Comment by DL6ER** [comment]
Merge conflict resolved

**Review by PromoFaux — APPROVED** [review]

**Comment by DL6ER** [comment]
Note: There is a discussion going on about this feature here: https://github.com/pi-hole/FTL/commit/caa98dc29f118fb8a90693ea15c93a5c8bc34629#r52628997

**Comment by yubiuser** [comment]
I updated today (`FTL version is development vDev-e826ae5 (Latest: v5.8.1)` and since then `pi.hole` is not resolved anymore.

```
chrko@ThinkPad-X230:~$ dig pi.hole

; <<>> DiG 9.11.3-1ubuntu1.15-Ubuntu <<>> pi.hole
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 6822
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pi.hole.			IN	A

;; Query time: 1 msec
;; SERVER: 10.0.1.5#53(10.0.1.5)
;; WHEN: Fri Jun 25 21:45:38 CEST 2021
;; MSG SIZE  rcvd: 36
```

**Comment by DL6ER** [comment]
Is `10.0.1.5` your Pi-hole? Does it work when you `dig pi.hole` locally on your Pi-hole?

For debugging, please add
```
DEBUG_NETWORKING=true
DEBUG_QUERIES=true
```
to the file `/etc/pihole/pihole-FTL.conf`, restart FTL and try again to `dig` from your X230.

You should see a line like
```
Replying to pi.hole with interface-local IP address
```
in `pihole-FTL.log` and something like
```
Jun 26 10:17:03 dnsmasq[3177022]: 25791 127.0.0.1/39511 query[A] pi.hole from 127.0.0.1
Jun 26 10:17:03 dnsmasq[3177022]: 25791 127.0.0.1/39511 gravity blocked pi.hole is 127.0.0.1
```
in `pihole.log` (with different addresses when from remote, of course).

I did the testing on the `update/dnsmasq-v2.86` branch but this shouldn't matter. Please try it as well when you have the time. And this reminds me that I need to change the `gravity blocked` text logged into `pihole.log` because this is not accurate here.

**Comment by yubiuser** [comment]
> Is 10.0.1.5 your Pi-hole?

Yes

> Does it work when you dig pi.hole locally on your Pi-hole?

No.

```
rockpi@rockpi-4b:~$ dig pi.hole

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> pi.hole
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 37565
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;pi.hole.			IN	A

;; AUTHORITY SECTION:
.			86392	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2021062600 1800 900 604800 86400

;; Query time: 19 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sat Jun 26 13:41:59 CEST 2021
;; MSG SIZE  rcvd: 111

rockpi@rockpi-4b:~$ dig pi.hole @10.0.1.5

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> pi.hole @10.0.1.5
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1462
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pi.hole.			IN	A

;; Query time: 0 msec
;; SERVER: 10.0.1.5#53(10.0.1.5)
;; WHEN: Sat Jun 26 13:42:19 CEST 2021
;; MSG SIZE  rcvd: 36

rockpi@rockpi-4b:~$ dig pi.hole @127.0.0.1

; <<>> DiG 9.11.5-P4-5.1+deb10u5-Debian <<>> pi.hole @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21728
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;pi.hole.			IN	A

;; Query time: 1 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Jun 26 13:42:44 CEST 2021
;; MSG SIZE  rcvd: 36

```

>  try again to dig from your X230

```
[2021-06-26 13:46:32.998 17950M] listening on 0.0.0.0 port 53
[2021-06-26 13:46:32.998 17950M] listening on :: port 53

[2021-06-26 13:46:33.005 17956/T17958] Interface lo is IPv4
[2021-06-26 13:46:33.005 17956/T17958] Interface eth0 is IPv4
[2021-06-26 13:46:33.006 17956/T17958] Interface wlan0 is IPv4
[2021-06-26 13:46:33.006 17956/T17958] Interface br-14708bb1934c is IPv4
[2021-06-26 13:46:33.006 17956/T17958] Interface docker0 is IPv4
[2021-06-26 13:46:33.006 17956/T17958] Interface veth47b289e is IPv4
[2021-06-26 13:46:33.006 17956/T17958] Interface vetha6731ff is IPv4
[2021-06-26 13:46:33.006 17956/T17958] Interface lo is IPv4
[2021-06-26 13:46:33.006 17956/T17958] Interface eth0 is IPv4
[2021-06-26 13:46:33.007 17956/T17958] Interface wg0 is IPv4
[2021-06-26 13:46:33.007 17956/T17958] Interface br-14708bb1934c is IPv4
[2021-06-26 13:46:33.007 17956/T17958] Interface br-14708bb1934c is IPv4
[2021-06-26 13:46:33.007 17956/T17958] Interface docker0 is IPv4
[2021-06-26 13:46:33.007 17956/T17958] Interface veth47b289e is IPv4
[2021-06-26 13:46:33.007 17956/T17958] Interface vetha6731ff is IPv4
[2021-06-26 13:46:33.007 17956/T17958] Found 15 IPv4 and 0 IPv6 capable interfaces

[2021-06-26 13:46:35.097 17956M] Interface (2) eth0 has IPv4 address 10.0.1.5 (other)
[2021-06-26 13:46:35.097 17956M] Replying to pi.hole with interface-local IP address

[2021-06-26 13:53:07.093 17956M] Replying to pi.hole with interface-local IP address

```

There are no queries logged as in `query[A] pi.hole from` (Also not when trying at the pihole device @127.0.0.1)

Interface listening mode is `all interfaces`

**Comment by DL6ER** [comment]
> There are no queries logged as in `query[A] pi.hole from` (Also not when trying at the pihole device @127.0.0.1)

Then how these lines look like? (there has to be *something* in the log):
``` bash
grep "13:53:07" /var/log/pihole.log
```

---

Please check out the latest `update/dnsmasq-v2.86` where I added some more debug output around the answer generation. Please also add
```
DEBUG_FLAGS=true
```

What we expect now:
```
[2021-06-26 16:23:59.424 3482866M] Processing FTL hook from src/dnsmasq/forward.c:1533...
[2021-06-26 16:23:59.424 3482866M]      Flags: F_FORWARD F_IPV4 F_QUERY 
[2021-06-26 16:23:59.424 3482866M] Replying to pi.hole with interface-local IP address
[2021-06-26 16:23:59.424 3482866M] Preparing reply for "pi.hole"
[2021-06-26 16:23:59.425 3482866M]      Flags: F_IPV4 
[2021-06-26 16:23:59.425 3482866M]   Adding RR: "pi.hole A 127.0.0.1"
[2021-06-26 16:23:59.425 3482866M] Processing FTL hook from src/dnsmasq_interface.c:240...
[2021-06-26 16:23:59.425 3482866M]      Flags: F_HOSTS F_IPV4 
```
in `pihole-FTL.log` and at the same time
```
Jun 26 16:23:59 dnsmasq[3482866]: 166 127.0.0.1/40830 query[A] pi.hole from 127.0.0.1
Jun 26 16:23:59 dnsmasq[3482866]: 166 127.0.0.1/40830 internal pi.hole is 127.0.0.1
```
in `pihole.log`

**Comment by yubiuser** [comment]
> Then how these lines look like? (there has to be something in the log)

```
rockpi@rockpi-4b:~$ grep "13:53:07" /var/log/pihole.log
rockpi@rockpi-4b:~$
```
Nothing there. Also nothing in the query log.
__

```
rockpi@rockpi-4b:~$ pihole -v
  Pi-hole version is development v5.3.1-15-g0612685 (Latest: v5.3.1)
  AdminLTE version is devel v5.5-21-g2c97652 (Latest: v5.5)
  FTL version is update/dnsmasq-v2.86 vDev-3076100 (Latest: v5.8.1)
rockpi@rockpi-4b:~$ grep pi.hole /var/log/pihole.log
Jun 26 18:07:14 dnsmasq[29410]: started, version pi-hole-2.86 cachesize 10000
Jun 26 18:07:26 dnsmasq[29410]: query[A] pi.hole from 10.0.1.31
```


```
[2021-06-26 18:07:26.095 29410M] Interface (2) eth0 has IPv4 address 10.0.1.5
[2021-06-26 18:07:26.096 29410M] Processing FTL hook from src/dnsmasq/forward.c:1534...
[2021-06-26 18:07:26.096 29410M]      Flags: F_FORWARD F_IPV4 F_QUERY 
[2021-06-26 18:07:26.096 29410M] Replying to pi.hole with interface-local IP address
[2021-06-26 18:07:26.096 29410M] Preparing reply for "pi.hole"
[2021-06-26 18:07:26.096 29410M]      Flags: F_NOERR 
[2021-06-26 18:07:35.082 29410M] Interface (2) eth0 has IPv4 address 10.0.1.5
[2021-06-26 18:07:35.083 29410M] Processing FTL hook from src/dnsmasq/forward.c:1534...
[2021-06-26 18:07:35.083 29410M]      Flags: F_FORWARD F_IPV4 F_QUERY
```

**Comment by yubiuser** [comment]
Latest update fixed it.

```
FTL version is update/dnsmasq-v2.86 vDev-a46cd20 (Latest: v5.8.1)


Jun 26 20:46:26 dnsmasq[4110]: started, version pi-hole-2.86 cachesize 10000
Jun 26 20:46:34 dnsmasq[4110]: query[A] pi.hole from 10.0.1.31
Jun 26 20:46:34 dnsmasq[4110]: internal pi.hole is 10.0.1.5

[2021-06-26 20:46:34.785 4110M] Interface (2) eth0 has IPv4 address 10.0.1.5
[2021-06-26 20:46:34.785 4110M] Processing FTL hook from src/dnsmasq/forward.c:1534...
[2021-06-26 20:46:34.785 4110M]      Flags: F_FORWARD F_IPV4 F_QUERY 
[2021-06-26 20:46:34.785 4110M] Replying to pi.hole with interface-local IP address
[2021-06-26 20:46:34.785 4110M] Preparing reply for "pi.hole"
[2021-06-26 20:46:34.785 4110M]      Flags: F_IPV4 
[2021-06-26 20:46:34.785 4110M]   Adding RR: "pi.hole A 10.0.1.5"
[2021-06-26 20:46:34.785 4110M] Processing FTL hook from src/dnsmasq_interface.c:260...
[2021-06-26 20:46:34.785 4110M]      Flags: F_HOSTS F_IPV4 

```

**Comment by DL6ER** [comment]
> But there is nothing in the query log

Yes, `pi.hole` lookups have always been hidden from the Query Log because visiting the web dashboard alone can fire like 25 queries just for getting the individual javascript files...

**Comment by yubiuser** [comment]
Makes sense!

**Comment by yubiuser** [comment]
Change in documentation needed.

> When using IP blocking mode, FTL determines the address of the interface a query arrived on. We then use this IP address in the blocked reply. 

https://docs.pi-hole.net/ftldns/configfile/#reply_addr4

**Comment by DL6ER** [comment]
See https://github.com/pi-hole/docs/pull/573/commits/f3d042e731923a12276441e478ab76b857c4af4a in https://github.com/pi-hole/docs/pull/573

**Pull request merged**
