### PR TITLE
Check pointers before accessing content

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

 In case requested object is out of range (`ID < 0` or `ID > maximum`) or has an incorrect magic byte, get getter functions in `shmem.c` return `NULL`. We have check against such `NULL`s before accessing the objects to avoid memory issues and segmentation faults.

Unfortunately, there are many getters and, hence, we have to add many guards. In a more high-level language, something like this will probably done by the language/compiler for us, but as C is a rather low-level language (you may want to call it "Comfort-Assembler"), we have to so this checking ourselves. This freedom opens a few possibilities, like we can skip updating only parts of the information if only some pointers are not available.

Finally, I should note that none of the checks added in this PR are expected to be triggered. However, I have once seen one failed magic byte (in several years looking almost daily at the logs) so there is a certain necessity for the checks to ensure the absence of SEGFAULTs in the crucial service a DNS server offers.

---

Footnote: The failing tests will be fixed when #634 is merged into this branch.

### CODE REVIEW

**Comment by Mcat12** [comment]
Wouldn't it be better to change it to simply fail (exit) if the memory is corrupt? If the memory is corrupt, there isn't much point in continuing.

**Comment by DL6ER** [comment]
Checking pointers that might come back as `NULL` seems to be the right thing to do.

This PR is motivated by a few (namely three) reports I've been sent by mail over the last year where users saw non-reproducible bugs. After switching on all debugging options, we were able to identify that there seems to be a certain possibility that `dnsmasq` logs a `forwarded ... to ...` without having issued a `new query ...` before. When this happens at the very beginning of the FTL run (and only then), we have not stored a single query and the first call to `getQuery(i, true)` (where `i=0`) will already return a `NULL` (as the magic byte *cannot* match). Our code apparently tries to access this `NULL` [here](https://github.com/pi-hole/FTL/pull/635/files#diff-092b49420239862fdbdcc87fdc72e10cL320) and hits a `SEGFAULT`.

However, in this case -- and also when a bug (not a memory corruption) "just" caused some magic bytes to be incorrect --, we could have safely continued without hard failing by just skipping this one reply.

An alternative to checking against `NULL` is to change the functions to something like `getQuery(ID, true, &okay)` and then check the `okay` boolean, however, this is just a more verbose way of ding the same thing in my eyes.

As accessing a `NULL` pointer is always bad and can cause a `SEGFAULT` anywhere, I added according checking code also to the telnet API and the other places where I found `get{Query,Domain,Forward,Client}(...)`.

**Comment by Mcat12** [comment]
If there are only a few known cases where this can happen, we should add an explicit check at those points instead of loosening our safety guarantees. In the forwarded without query case, first check to make sure we have recorded a query and stop if we have not recorded any queries.

**Comment by DL6ER** [comment]
There is only one known case I know of where a crash happened, actually. Why do you think we shouldn't add a check everywhere a crash would occur otherwise? Just because of if memory corruption occurred, there is no point in letting it run further?

I'm not sure whether it'll be easy to *exactly* predetermine exactly where the crashes are non-fatal and where they are fatal, but I'll check it again tomorrow.

**Comment by dschaper** [comment]
@DL6ER Status? Is this good to check?

**Comment by DL6ER** [comment]
Yes

**Comment by dschaper** [comment]
After this merges we will need to set `ci/circleci: arm-qemu` back to required for `development` branch.

**Pull request merged**
