### PR TITLE
Do not rewrite config files if unchanged

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Do not rewrite config files if they are unchanged. This PR implements this for
- `/etc/pihole/pihole.toml`
- `/etc/pihole/dnsmasq.conf`
- `/etc/pihole/custom.list`

The goal is to effectively preserve a larger number of config file backups as needless rotations (without any changes) are prevented.

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by yubiuser** [comment]
How does this PR relate to https://github.com/pi-hole/FTL/pull/1754?

Should the latter be merged first? Then there might be no need to include `custom.list` as it is not backed up anymore?

**Comment by DL6ER** [comment]
Yes, we should merge the other PR first and then resolve the merge conflicts here. It may still be useful to not rewrite `custom.list` when it dis not change - even if this is basically irrelevant without rotation.

**Review by yubiuser — COMMENTED** [review]
Do I understand this correctly: you write temporary config files to disk, compare them with the current config file, replace them only if they are different and delete the temporary file at the end?

**Comment by DL6ER** [comment]
Yes, that's the most simple way of doing this. Otherwise, we have to reallocate memory from time to time when we hit the buffer size. Writing to really existing files we can either swap in or remove is the by far easiest way of doing things.

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
