### PR TITLE
Fix the Stale workflow

### PR DESCRIPTION
**Pull request by PromoFaux**
See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment-on-issues-only-or-pull-requests-only

### CODE REVIEW

**Review by DL6ER — APPROVED** [review]

**Comment by yubiuser** [comment]
Looking at the triggers and the conditionals, I think this is still triggered on schedule.

**Comment by PromoFaux** [comment]
Ah, yes - you're right. I was conflating two separate issues with the config.

I also noted that it was running against Pull requests, too (which this fixes). I'll rebase on `master` once https://github.com/pi-hole/FTL/pull/1587 is merged, as that also contains the commit to fix the codespell issue

**Comment by yubiuser** [comment]
>  (which this fixes)

Did you try this? I'm not sure, as we have now

`if: github.event_name == 'issue_comment' && ${{ !github.event.issue.pull_request }}`

which also contains the part `${{ !github.event.issue.pull_request }}` which will be left after your PR. Already the current state should not (but indeed does) trigger on PRs....

**Comment by PromoFaux** [comment]
I did, but then I deleted the comment. Here, I did it again:

https://github.com/pi-hole/docker-pi-hole/actions/runs/5536224129 - which was triggered by: https://github.com/pi-hole/docker-pi-hole/pull/1366#issuecomment-1633184606

**Review by DL6ER — APPROVED** [review]

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
