### PR TITLE
Add support for legacy Teleporter archives

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

This PR adds importing of Pi-hole pre-v6.0 Teleporter files. I don't run v5 myself for many years, so I didn't had a very useful Teleporter archive for testing this feature and we may be expecting some rough edges. 

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by LizenzFass78851** [comment]
@DL6ER 
I found a suitable one [teleporter.tar.gz](https://github.com/RPiList/specials/blob/master/teleporter_ohne-Banken_2023-07.tar.gz) from the @RPiList project.

After switching the FTL to the new/teleporter_v5 branch and after reloading the web interface I imported the teleporter file. The following result came:
Screenshot (1)

and by trying `pihole -g` I also saw that it didn't adopt the change from the teleporter file.
The changes are also not visible in the web interface. The changes were probably not adopted

Debug Tokens: https://tricorder.pi-hole.net/11eNa2PD/

**Comment by DL6ER** [comment]
@LizenzFass78851 Thanks for testing and suggesting this file! I found the issue - I had implemented import for string and number columns but forgot about `NULL` columns. This should now be working.

**Comment by LizenzFass78851** [comment]
it works. Only among others, the previously added adlists were not overwritten, if this was intended.

**Comment by DL6ER** [comment]
Yes, that's intended. Could you quote the related lines from your `/var/log/pihole/FTL log` file?

**Comment by LizenzFass78851** [comment]
> Yes, that's intended. Could you quote the related lines from your `/var/log/pihole/FTL.log` file?

See new Debug Token: https://tricorder.pi-hole.net/7hqkHNka

**Comment by DL6ER** [comment]
Unfortunately the debug log only contains a few lines from the beginning and end of the log file. What we are looking for isn't included. You could try 
```
pihole tricorder < /var/log/pihole/FTL.log
```

If it returns a token, the upload was successful. As there is a size limitation in Tricorder, the upload might fail for very large log files, though.

**Comment by LizenzFass78851** [comment]
I get the following error via the tricoder:
`  [i] Please do not call Tricorder directly`

So I copy the log here:
[FTL.log](https://github.com/pi-hole/FTL/files/13423322/FTL.log)

**Comment by DL6ER** [comment]
Oh, I put the command the wrong way around, I fixed it in my previous comment. There is nothing obvious in your FTL.log file (no warnings/errors), maybe you can get some more insight by enabling `pihole-FTL --config debug.api true` before trying the import.

I tested this again and still cannot reproduce, let me document how I tested it:

```
# sqlite3 /etc/pihole/gravity.db 
SQLite version 3.41.2 2023-03-22 11:56:21
Enter ".help" for usage hints.
sqlite> SELECT * FROM adlist;
1|0|https://pi-hole.net/block.txt|1|1559928803|1559928803|Fake block-list|1559928803|2000|2|1|0
2|1|https://pi-hole.net/allow.txt|1|1559928803|1559928803|Fake allow-list|1559928803|2000|2|1|0
```
(those are dummy entries from our automated tests)

but after import of the file above they are gone and replaced by these:
```
# sqlite3 /etc/pihole/gravity.db 
SQLite version 3.41.2 2023-03-22 11:56:21
Enter ".help" for usage hints.
sqlite> SELECT * FROM adlist;
1|0|https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts|1|1690837001|1690837001|Migrated from /etc/pihole/adlists.list|1690837001|203872|1|1|0
2|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/notserious|1|1690837374|1690837374|||0|0|0|0
3|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Streaming|1|1690837374|1690837374|||0|0|0|0
4|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Phishing-Angriffe|1|1690837374|1690837374|||0|0|0|0
5|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/spam.mails|1|1690837374|1690837374|||0|0|0|0
6|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Win10Telemetry|1|1690837374|1690837374|||0|0|0|0
7|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/easylist|1|1690837374|1690837374|||0|0|0|0
8|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/samsung|1|1690837374|1690837374|||0|0|0|0
9|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock1|1|1690837374|1690837374|||0|0|0|0
10|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock2|1|1690837374|1690837374|||0|0|0|0
11|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock3|1|1690837374|1690837374|||0|0|0|0
12|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock4|1|1690837374|1690837374|||0|0|0|0
13|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock5|1|1690837374|1690837374|||0|0|0|0
14|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/pornblock6|1|1690837374|1690837374|||0|0|0|0
15|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/proxies|1|1690837374|1690837374|||0|0|0|0
16|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/crypto|1|1690837374|1690837374|||0|0|0|0
17|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/gambling|1|1690837374|1690837374|||0|0|0|0
18|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/child-protection|1|1690837374|1690837374|||0|0|0|0
19|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Fake-Science|1|1690837374|1690837374|||0|0|0|0
20|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/Corona-Blocklist|1|1690837374|1690837374|||0|0|0|0
21|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/malware|1|1690837374|1690837374|||0|0|0|0
22|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/MS-Office-Telemetry|1|1690837374|1690837374|||0|0|0|0
23|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting1|1|1690837374|1690837374|||0|0|0|0
24|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting2|1|1690837374|1690837374|||0|0|0|0
25|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting3|1|1690837374|1690837374|||0|0|0|0
26|0|https://raw.githubusercontent.com/RPiList/specials/master/Blocklisten/DomainSquatting4|1|1690837374|1690837374|||0|0|0|0
```

The log says (only an excerpt):
```
2023-11-21 08:15:13.949 [93149/T93155] INFO: import_json_table(adlist.json): JSON array contains 26 entries
2023-11-21 08:15:13.949 [93149/T93155] DEBUG_API: import_json_table(adlist.json): Deleting all entries from table "adlist"
2023-11-21 08:15:13.949 [93149/T93155] DEBUG_DATABASE: dbquery: "DELETE FROM "adlist";"
2023-11-21 08:15:13.950 [93149/T93155] DEBUG_DATABASE:          ---> OK
```

**Comment by LizenzFass78851** [comment]
I just remembered the only standard list that I stored before I imported the teleporter is the one from Stevenblack and this is also included in the teleporter. 
That's why I thought that this list hadn't been deleted, but the list was also included in the teleporter.  

What I also noticed is that when I imported the teleporter file, it changes the port of the web interface from 80 to 8080 and the next time I import it changes back to 80. 
(But it could also be that this setting is with the different port  is also probably included in the teleporter and the port therefore changes after the import)

**Comment by DL6ER** [comment]
> What I also noticed is that when I imported the teleporter file, it changes the port of the web interface from 80 to 8080 and the next time I import it changes back to 80.

Hmm, this is a very interesting observation. I checked what is going on ~~and I yet have to find a good solution~~. When there are no ports configured, FTL checks whether ports 80, 8080, 443 and 8443 are used and accordingly selects ports to (hopefully) avoid conflicts. This is implemented to avoid conflicts with previously `lighttpd` installations, etc.

We now observe that when FTL used port 80 and is restarted, moments after the restart, port 80 will still be shown as being used - even when this is actually not true any longer as the previous process has already exited. It then selected 8080 to avoid a conflict. On the next importing try, it sees that 8080 is taken and picks 80. That's why it is alternating.

**edit** The proposed solution is to simply add the currently used ports to the generated `setupVars.conf` from where it is re-imported into the new configuration. This ensures the port detection logic isn't triggered.

**Comment by LizenzFass78851** [comment]
> > What I also noticed is that when I imported the teleporter file, it changes the port of the web interface from 80 to 8080 and the next time I import it changes back to 80.
> 
> Hmm, this is a very interesting observation. I checked what is going on ~and I yet have to find a good solution~. When there are no ports configured, FTL checks whether ports 80, 8080, 443 and 8443 are used and accordingly selects ports to (hopefully) avoid conflicts. This is implemented to avoid conflicts with previously `lighttpd` installations, etc.
> 
> We now observe that when FTL used port 80 and is restarted, moments after the restart, port 80 will still be shown as being used - even when this is actually not true any longer as the previous process has already exited. It then selected 8080 to avoid a conflict. On the next importing try, it sees that 8080 is taken and picks 80. That's why it is alternating.
> 
> **edit** The proposed solution is to simply add the currently used ports to the generated `setupVars.conf` from where it is re-imported into the new configuration. This ensures the port detection logic isn't triggered.

I tried this again by importing the teleporter file and the web interface still alternately changes the port to 8080 and the second time again to 80.

Here is the FTL.log:
[FTL.log](https://github.com/pi-hole/FTL/files/13427564/FTL.log)

Debug Token: https://tricorder.pi-hole.net/YERIXkgn/
Debug Token for full FTL.log: https://tricorder.pi-hole.net/mGUBWiYq/

**Comment by DL6ER** [comment]
Alright, sorry about that, the mistake was to write `WEB_PORT` but then trying to read `WEB_PORTS` (mind the extra `S`). Should now be fixed.

**Comment by LizenzFass78851** [comment]
> Should now be fixed.

yes, it worked successfully

**Review by PromoFaux — APPROVED** [review]
Approving based on testing user's comments of:

> yes, it worked successfully

**Pull request merged**
