### PR TITLE
Pi-hole FTL v3.0

### PR DESCRIPTION
**Pull request by DL6ER**
Release

### CODE REVIEW

**Comment by DL6ER** [comment]
Approved

**Comment by jacobsalmela** [comment]
:shipit:

**Comment by nugget** [comment]
The release is broken for `pihole-up` or anything that invokes `basic-install.sh` because none of the binary Assets have been uploaded to the release here on GitHub.

Trying to upgrade yields a curl 404 error trying to download `https://github.com/pi-hole/FTL/releases/download/v3.0/pihole-FTL-linux-x86_64` (or whichever binary is suitable for the user's platform).

```
  [i] FTL:		update available

  [i] FTL out of date

  [i] FTL Checks...
  [✓] Detected x86_64 architecture
  [i] Checking for existing FTL binary...
  [i] Downloading and Installing FTL...curl: (22) The requested URL returned error: 404 Not Found
  [✗] Downloading and Installing FTL
  Error: URL not found
```

**Comment by Mcat12** [comment]
We're resolving that now, see #229

**Pull request merged**
