### PR TITLE
Improve virtual interface analysis

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Allow alias interfaces to be analyzed by making a bug in `dnsmasq` consistent. More information can be found in the linked Discourse discussion.

### CODE REVIEW

**Comment by DL6ER** [comment]
Confirmed working by original reporter in https://discourse.pi-hole.net/t/finding-pi-hole-ip-addresses-after-v5-4-update/49712/60

**Comment by DL6ER** [comment]
Note: This change should be sent upstream to `dnsmasq` at some point in the future to improve also the upstream project's handling of virtual interfaces/interface aliases. This will be independent to this fix and will only be done as soon as Simon Kelley returned.

**Comment by yubiuser** [comment]
So this PR makes the bug consistent, but is only a workaround until the bug is really fixed. Fixing the underlying bug is what your linked `dnsmasq` PR does?

**Comment by DL6ER** [comment]
The "make the bug consistent" I did in here is going to be sent to `dnsmasq`. I don't think the bug will ever be really fixed due to technical limitations of the Linux networking stack.

Background: When we receive a reply, we get two details about the receiving interface: The interface index (from the kernel) and the address on which the packet arrived on (from the DNS packet header). Unfortunately, alias/virtual interfaces are still the same *physical* device and, hence, `dnsmasq` cannot distinguish based on the interface index alone.
FTL does this differently, but it means extra work. Instead of relying on the kernel-provided interface index, we compile a list of IP addresses on the machine and then iterate over them until we find a match for the address we received the query on. This allows us to see if the address is bound to an alias/virtual interface.

`dnsmasq` has two options: Either they implement the same iterating over all interface address we do now *inside FTL* or they acknowledge that there is a bug and make the bug consistent (this means "alias/virtual" interfaces are indistinguishable from "real" ones in the config). This is wrong but less code change.

We'll see.

**Comment by DL6ER** [comment]
Sorry for the long text above. I'll try again shorter and from another perspective:

1. The bug is that `dnsmasq` also listens on `eth0:0` when the config asks it to listen only on `eth0` (reasons above)
2. As we should not be listening on `eth0:0`, FTL has no information about this interface.
3. Because of this, the local address in not available when a query arrives, and
4. we fail to provide the correct response.

When we fix no. 1 in `dnsmasq` (stop accepting queries on the virtual interface), nothing of this is actually needed. However, fixing no. 1 does not straightforward at this time.

**Review by yubiuser — APPROVED** [review]

**Comment by yubiuser** [comment]
Thanks for the explanation. I have little hope `dnsmasq` will pick up the iteration but maybe include this PR.

**Comment by DL6ER** [comment]
They already have such a code, the implementation is, however, a bit incorrect.

1. Config `interface=eth0`
Queries on `eth0` and `eth0:0` are accepted because `dnsmasq` only compares the physical interface name string.

2. Config `interface=eth0:0`
Queries on `eth0` and `eth0:0` are rejected (at first!) because of the mismatch. However, there is another check "`label_expection()`" that does said iteration and would lead to accepting the `eth0:0` query. The `eth0` query is correctly rejected.

The fix would be to generalize the `label_exception()` to be always be used *instead* of the interface name string.

**Pull request merged**
