### PR TITLE
Add warning for invalid hostnames to FTL message table

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Add a message for Pi-hole diagnostics when host names with invalid characters have been found during FTL's internal name resolution (typically client host names containing non-ASCII characters).

Example:
```
$ grep /etc/hosts "127.0.0.53
127.0.0.53 Cöfte
```

results in
id|timestamp|type|message|blob1|blob2|blob3|blob4|blob5
--|--|--|--|--|--|--|--|--
98|1590222660|HOSTNAME|127.0.0.53|Cöfte|1|||

where `message (TEXT)` = IP of the host names, `blob1 (UTF8 TEXT)` = the obtained host names, `blob2 (INT)` = position of the invalid character

### CODE REVIEW

**Comment by yubiuser** [comment]
Starting counting for blob 2 with zero might irritated some users as it is more natural starting counting with one in natural languages.
Invalide character is ö and most users will tend to see it on position 2.

**Comment by DL6ER** [comment]
I agree, however, users should not really interpret the message table themselves, see https://github.com/pi-hole/AdminLTE/pull/1356

**Comment by DL6ER** [comment]
Furthermore, as both languages in involved here (`C` and `Javascript`) count from zero and this table is not supposed to be used directly by the user, it seems strange to do an artificial `+1` in `C` followed by a similarly artificial `-1` in JS.

However, thanks for your input!

**Comment by yubiuser** [comment]
> I agree, however, users should not really interpret the message table themselves, see pi-hole/AdminLTE#1356

Ok :-) Haven't imagine such an overkill presentation of the error message

**Comment by DL6ER** [comment]
I will do one more optimization concerning locks, until then, this PR is again in draft mode. Feel free to still merge the AdminLTE PR, they are completely independent and it would anyways be better if the AdminLTE PR is merged before.

**Comment by yubiuser** [comment]
What happens if there is more than one illegal character?

**Comment by DL6ER** [comment]
We only check the string until we find the first invalid character. This is also the one we report to the user. I don't think we need to add multi-error handling. When the fix the first incorrect character (and there are multiple), the next iteration will yield the next invalid character.

**Comment by PromoFaux** [comment]
image

@DL6ER did you forget to sign a commit?

**Comment by DL6ER** [comment]
Re-signed all commits using
```
git rebase --exec 'git commit --amend --no-edit -n -S' -i development
```

**Comment by DL6ER** [comment]
@PromoFaux Kindly asking for a re-approval

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-5-1-released/35577/1

**Pull request merged**
