### PR TITLE
Log query loop detection to Pi-hole diagnosis system

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Still disable looping servers, however, add a hint to the message table of the Pi-hole diagnosis system to increase visibility.

Note: I'm currently unable to test looping (my router cannot be configured to loop back to the Pi-hole), so I'm marking this as draft until someone (not necessarily me!) can actually test this.

### CODE REVIEW

**Comment by yubiuser** [comment]
I've tried this branch, but got no message

```
  Current Pi-hole version is development v5.1.2-129-g3190909.
  Current AdminLTE version is devel v5.1.1-128-g1ea21911.
  Current FTL version is tweak/queryloop_message vDev-0e1fece.
```

```
[2020-11-25 18:51:18.274 4980M]  -> Known forward destinations: 1
[2020-11-25 18:51:18.274 4980M] Successfully accessed setupVars.conf
[2020-11-25 18:51:18.284 4982M] PID of FTL process: 4982
[2020-11-25 18:51:18.285 4982/T4983] Listening on port 4711 for incoming IPv4 telnet connections
[2020-11-25 18:51:18.286 4982M] INFO: FTL is running as user pihole (UID 998)
[2020-11-25 18:51:18.286 4982/T4985] Listening on Unix socket
[2020-11-25 18:51:18.286 4982/T4984] Listening on port 4711 for incoming IPv6 telnet connections
[2020-11-25 18:51:18.287 4982M] Reloading DNS cache
[2020-11-25 18:51:18.288 4982M] Blocking status is enabled
[2020-11-25 18:51:18.291 4982M] QUERY LOOP WARNING: Disabled upstream server 10.0.1.1#53 as we detected a query loop!

```

```
nanopi@nanopi:~$ sqlite3 /etc/pihole/pihole-FTL.db --header --column "Select * from message;"
nanopi@nanopi:~$ 

```

**Comment by DL6ER** [comment]
@yubiuser This is strange, can you trigger some other message (such as regex syntax error) to verify that the `message` table works at all for you? I should not hide that I'm more and more getting to the impression that I just want to revert the DNS loop detection mechanism as it will send out queries also to public DNS servers which is likely something we want to avoid. In this case, I'd close this PR without merging to avoid introducing unnecessary code.

**Comment by yubiuser** [comment]
```
[2020-11-25 20:32:05.416 4982/T4986] REGEX WARNING: Invalid regex blacklist filter "(((": Missing ')'
```

```
nanopi@nanopi:~$ sqlite3 /etc/pihole/pihole-FTL.db --header --column "Select * from message;"
id          timestamp   type        message      blob1       blob2       blob3       blob4       blob5     
----------  ----------  ----------  -----------  ----------  ----------  ----------  ----------  ----------
3           1606332725  REGEX       Missing ')'  blacklist   (((         0          
```

Restarted pihole

```
[2020-11-25 20:33:23.281 8956M] QUERY LOOP WARNING: Disabled upstream server 10.0.1.1#53 as we detected a query loop!
[2020-11-25 20:33:23.394 8956/T8960] REGEX WARNING: Invalid regex blacklist filter "(((": Missing ')'
```
```
nanopi@nanopi:~$ sqlite3 /etc/pihole/pihole-FTL.db --header --column "Select * from message;"
id          timestamp   type        message      blob1       blob2       blob3       blob4       blob5     
----------  ----------  ----------  -----------  ----------  ----------  ----------  ----------  ----------
5           1606332803  REGEX       Missing ')'  blacklist   (((         0   
```

**Comment by yubiuser** [comment]
Tried to add `DEBUG_DATABASE=true` but nothing useful in regard to the `message` table is logged.

**Comment by DL6ER** [comment]
Putting this into the backlog as we've removed this setting by default

**Pull request closed without merging**
