### PR TITLE
Add Luascript support in FTL

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

This adds Luascript capabilities to be used inside (and outside) of FTL. Exemplary usages may be a rewrite of Pi-hole scripts in Lua.

### CODE REVIEW

**Comment by DL6ER** [comment]
```
$ pihole-FTL lua
Pi-hole FTL v5.2-261-g176be7b2
Lua 5.4.1  Copyright (C) 1994-2020 Lua.org, PUC-Rio
> a=5
> a
5
> inspect(pihole)
{
  ftl_version = <function 1>
}
> pihole.ftl_version()
v5.2-261-g176be7b2
> 
```

For `inspect` to work, you'll need https://ftl.pi-hole.net/libraries/inspect.lua in `/opt/pihole/libs` - this will be taken care of later (when I find the time to code the extension downloader for the core repo).

**Comment by DL6ER** [comment]
Or direct code execution like
```
$ pihole-FTL lua -e "print(pihole.ftl_version())"
v5.2-261-g176be7b2
```

**Comment by dschaper** [comment]
```lua
#! pihole-FTL lua
print(pihole.ftl_version())
```

That should work, right?

**Review by dschaper — DISMISSED** [review]

**Comment by DL6ER** [comment]
You always need the full path for 

```lua
#! pihole-FTL lua
print(pihole.ftl_version())
```
```bash
./test.lua 
-bash: ./test.lua: pihole-FTL: bad interpreter: No such file or directory
```
but
```lua
#! /usr/bin/pihole-FTL lua
print(pihole.ftl_version())
```
```bash
./test.lua 
v5.2-257-g6e402386-dirty
```

**Comment by dschaper** [comment]
Oh, sorry, I got confused. I thought the `pihole` object needed `inspect` for it to work. I didn't check to see what the `inspect` module did. It's (`inspect`) is just doing the pretty-print representation of the `pihole` objects table?

**Review by dschaper — APPROVED** [review]

**Comment by DL6ER** [comment]
> It's (inspect) is just doing the pretty-print representation of the pihole objects table?

Yes, it's a feature I'd see mandatory in the core language but it is only available as an optional extension. The regular lua `print` function doesn't go much here, `inspect` is a much more useful tool, compare:
```
> print(pihole)
table: 0x55a2daa39590
```
```
> inspect(pihole)
{
  ftl_version = <function 1>
}
```

**Pull request merged**
