### PR TITLE
Only reload pihole.toml if changed

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Currently, we always reload `pihole.toml` if it was touched by anyone, even if nothing got changed. This PR changes this to only reload `pihole.toml` if the content really changed. Internally, we use `sha256sum` to memorize a checksum of the file.

Due to a cache-optimal design, we can even outperform the system-provided `sha256sum`:

```
$ time sha256sum pihole-FTL
4f72f290b8be5498b31c32e27ee9c6d7dafedcd454770d9a1f36efc8fe403edf  pihole-FTL

real    0m0.113s
user    0m0.104s
sys     0m0.009s

$ time pihole-FTL sha256sum pihole-FTL
4f72f290b8be5498b31c32e27ee9c6d7dafedcd454770d9a1f36efc8fe403edf  pihole-FTL

real    0m0.044s
user    0m0.036s
sys     0m0.008s
```

```
$ time sha256sum oci.tar
6a885fe60b78d1abd6a73c239ed465e0a10681942d66b3e6317b40fdbc9a01b9  oci.tar

real	0m2.090s
user	0m2.030s
sys	0m0.060s

$ time ./pihole-FTL sha256sum oci.tar
6a885fe60b78d1abd6a73c239ed465e0a10681942d66b3e6317b40fdbc9a01b9  oci.tar

real	0m0.456s
user	0m0.344s
sys	0m0.112s
```
(`oci.tar` is a 550 MB file)

I ran the commands several times to ensure the file was cached in memory to rule out possible disk influences.

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by yubiuser** [comment]
Can we use hashing also when comparing `pihole.toml` and `pihole.toml.temp` (and the other files). This might be faster than comparing line by line.

**Comment by DL6ER** [comment]
We'd anyway have to read line-by-line to be able to skip the first `N` lines to skip the timestamp in the header (or all files will always be different!). If reading in bulk, we have to iterate until we have found enough `\n` and then offset the SHA computation. Either or, comparing line-by-line is *much* faster because iterating in C comes at no costs (unless we are talking about billions of lines) and a direct memory comparison is an instruction the CPU can do at once, the entire SHA computation is, on the other hand, a pretty massive operation:

Proof-of-work-SHA256
((source)[https://cryptonomist.ch/2019/06/15/algoritmi-mining-proof-of-work/])

**Review by yubiuser — COMMENTED** [review]
Something is not right. Changing settings from the web interface is fine, but manually editing `pihole.toml` does not log the writing and does not  backup the log

The first line of the log is a setting changed from the web interface, the second via manual editing.

```
2023-11-23 21:14:39.657 [43543/T43800] INFO: Config file written to /etc/pihole/pihole.toml
2023-11-23 21:15:34.556 [43543/T43793] INFO: Reloading config due to pihole.toml change

```

**Comment by DL6ER** [comment]
> but manually editing `pihole.toml` does not log the writing and does not backup the log

I think this is because the recent bugfix https://github.com/pi-hole/FTL/pull/1775 was not included here. I just merged `development-v6`

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
