### PR TITLE
Slash the slash

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

As a consequence of https://github.com/pi-hole/AdminLTE/pull/2655, redirection from the login page to any other page than the dashboard is broken.

This PR fixes this in the proper way by redirecting from URLs with *trailing slashes* such as `/admin/queries/"` to `/admin/queries` which is where the actual scripts are (they'd have to be in `/admin/queries/index.html` otherwise)

---
**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by PromoFaux** [comment]
Testing in a container - it appears the behaviour that was fixed by https://github.com/pi-hole/AdminLTE/pull/2655 is back

Visiting `pi.hole/admin` redirects to `172.20.2/admin/`

**Comment by PromoFaux** [comment]
> Visiting `pi.hole/admin` redirects to `172.20.2/admin/`

This is still the case for me

The other issue that I showed in the gif in mattermost earlier, however, is fixed

**Comment by DL6ER** [comment]
@PromoFaux I cannot reproduce this, but it might be a cache issue. Could you try again with another browser or her with the dev tools opened on the networks tab and selected to not load from cache?

**Comment by PromoFaux** [comment]
Same thing in an incognito window with cache disabled

If I'm logged out, it works... at least, I get redirected to `127.0.0.1/admin/login?target=%2admin`

Once I log in, it takes me to `127.0.0.1/admin/`

If I then manually remove the trailing slash you see the following behaviour:

image

image

**Comment by DL6ER** [comment]
I'm confused now, that is only happen when you manually remove the slash or does it also happen when you do something in the way it should be done? (No doubt we should get the manual removal of the slash fixed as well)

**Comment by PromoFaux** [comment]
Seemingly only when I do the manual remove of the slash. Imagine I am authenticated, and then open a new tab and type `127.0.0.1/admin` - it should probably redirect

**Comment by yubiuser** [comment]
I can confirm, everything works as it should when used as one should use it. However, when I'm loggend in via `hostname/admin/` and remove the trailing slash I get redirected to `IP/login` as unauthorized.

**Comment by DL6ER** [comment]
It should now be fixed. This last change actually made https://github.com/pi-hole/AdminLTE/pull/2655 completely redundant, however, it also doesn't hurt to have it.

**Review by PromoFaux — APPROVED** [review]
Confirmed with a local build that this is now working as expected, even when used as not expected.

image

**Pull request merged**
