### PR TITLE
Add support for additional query types

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Add support for additional query types. This also implements support for blocking for **all** query types instead of the subset we supported blocking for in v5.0

We already supported:
- `A`,
- `AAAA`,
- `ANY`,
- `SRV`,
- `SOA`,
- `PTR`,
- `TXT`,
- `NAPTR`

New:
- `MX`,
- `DS`,
- `RRSIG`,
- `DNSKEY`, and 
- `OTHER` (summing up all other possible DNS types)

### CODE REVIEW

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/what-is-query-type-65479-in-the-logs/34884/10

**Comment by dschaper** [comment]
Are there any other types defined in RFC's that are not covered after this PR is merged?

**Comment by DL6ER** [comment]
Yes, actually plenty. There is `WKS`, `HINFP`, `NSAP`, `NSAP_PTR`, `SIG`, `KEY`, `LOC`, `KX`, `CERT`, `A6`, `DNAME`, `OPT`, `NSEC3` and 20+ more. However, they are all query types I have not seen before in real-life and adding them to Pi-hole seems questionable. We will group these under the new type `OTHER` which is still better than what we do now (ignoring them).

**Comment by dschaper** [comment]
Okay, was going on the idea that if you're going to add some then might as well add all and not have to revisit with new PRs later to extend the `qtype` array. But I'll leave that up to you.

LGTM.

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/regex-engine-improvements/34751/33

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/pi-hole-5-1-released/35577/1

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/a-few-other-dns-request-type-after-5-1/35635/2

**Comment by bondskin** [comment]
> This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:
> 
> https://discourse.pi-hole.net/t/what-is-this-other-category-about/38490/4

Any chance to separate this Type65 traffic rather than accumulating it with "Other", caused by iOS 14 (incl tvOS, MacOS) as these devices are generating a lot of traffic.

**Comment by DaCapitalist** [comment]
@DL6ER 
I Support @bondskin ‘s proposal. This makes totally sense to me. Does it make sense to open an issue for this or would you or someone else pick this up based on this thread? We would strongly appreciate this:)

**Comment by yubiuser** [comment]
Already in the pipeline
https://github.com/pi-hole/FTL/pull/1013

**Comment by DL6ER** [comment]
Adding to what @yubiuser said, `HTTPS` will still become an independent query type of it's own: https://github.com/pi-hole/FTL/pull/1010

This all will be part of the next release.

**Pull request merged**
