### PR TITLE
Add RISC-V 64-bit support and builds

### PR DESCRIPTION
**Pull request by MichaIng**
## Thank you for your contribution to the Pi-hole Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

**Please make sure you**

 1. Base your code and PRs against the repositories developmental branch.
 2. [Sign Off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits as we enforce the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
 3. [Sign](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all your commits as they must have verified signatures
 4. File a pull request for any change that requires changes to [our documentation](https://docs.pi-hole.net/) at our [documentation repo](https://github.com/pi-hole/docs) 

---

**What does this PR aim to accomplish?:**

Adds support for RISC-V 64-bit architecture and FTL builds to CI.

**How does this PR accomplish the above?:**

- Added `struct_size` detection according to RISC-V C API: https://github.com/riscv-non-isa/riscv-c-api-doc/blob/master/riscv-c-api.md#preprocessor-definitions
- Added binary test
- Added build to GitHub Actions workflow
- [x] Add Pi-hole `riscv64` Docker base image: https://github.com/pi-hole/docker-base-images/pull/63
    Tests/builds cannot be done since GitHub secrets are not available in actions from forks. Not sure how to unblock best.

Companion PRs:
- https://github.com/pi-hole/docker-base-images/pull/63
- https://github.com/pi-hole/pi-hole/pull/5196

**Link documentation PRs if any are needed to support this PR:**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [x] I have read the above and my PR is ready for review. *Check this box to confirm*

### CODE REVIEW

**Comment by DL6ER** [comment]
@MichaIng `ghcr.io/pi-hole/ftl-build:v1.26-riscv64` is now available. I also have a PR to avoid the :x: on the `spell-check` action but this hasn't landed in `devlopment` yet.

**Comment by DL6ER** [comment]
@MichaIng You'll have to update the containers from `v1.23` to `v1.26` in [`.github/workflows/build.yml`](https://github.com/pi-hole/FTL/pull/1536/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721):

Screenshot from 2023-03-20 19-47-18

**Comment by MichaIng** [comment]
Ah, make sense.

Now I see those `%ssudo` and `%sstart`. Feels like the very same as on our docs and website repos: Spell checking is generally great, but one has to maintain a huge exclusion/word list 😄. I was not brave enough to implement it in DietPi main repo, yet 🙈.

**Comment by DL6ER** [comment]
Should be fixed in `development` but but I'm happy to overwrite `code-spell` here. Thanks for your PR!

**Review by DL6ER — APPROVED** [review]

**Pull request merged**
