### PR TITLE
prevent free() after alloca()

### PR DESCRIPTION
**Pull request by catch-error**
Signed-off-by: catch-error <mirko.kraft@gmx.ch>

**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 3

---

alloca() allocates memory from the stack. Passing a pointer returned by alloca() to free() results in undefined behavior. This patch ensures that whenever TRE_USE_ALLOCA is active, free() never gets called by the BT_STACK_PUSH macro.

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by yubiuser** [comment]
Thanks for your PR. All your changes are in the `tre-regex` engine, which is maintained here: https://github.com/laurikari/tre/

Usually such things should be fixed upstreams, but the project is abandoned. 
https://github.com/laurikari/tre/blob/master/README.md

**Comment by catch-error** [comment]
I don't think there'll be a next release coming from upstream in the near future (if at all). I can create the same PR on the upstream side, however, so if, against the odds, the project gets going again, there's a chance the code will stay consistent.

**Comment by yubiuser** [comment]
We are discussing internally how to go on with `tre-regex`. We'll let you know.

**Comment by DL6ER** [comment]
@catch-error Please submit your patch against https://github.com/pi-hole/tre - we will review it there. This seems to be the cleanest way. Once merged, we will import the commits over to the FTL repository.

**Pull request closed without merging**
