### PR TITLE
Ensure database upgrades use transactions

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

This PR improves `pihole-FTL.db` handling in two ways:

1. Ensure all database upgrade steps are wrapped into transactions. When the database upgrade is interrupted (FTL is killed, or crashed or power loss, ...), then the rollback journal file is left on disk. The next time another application attempts to open the database file, it notices the presence of the abandoned rollback journal (we call it a "hot journal" in this circumstance) and uses the information in the journal to restore the database to its state prior to the start of the incomplete transaction. This fixes sporadic issues with only partially initialized databases mostly seen on devices with unstable power supply.
   So far, it is unclear how the initial database migration happens but it is likely due to the reasons mentioned above. We have reports of this seen every now and then (also with v5.x releases) but never really tracked it down before.

2. Add a new `descriptions` column to the `ftl` database table to make working with the database more human-friendly. This updates the database to version 14

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
4. I am willing to help maintain this change if there are issues with it later.
5. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
6. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by dschaper** [comment]
Is the transaction file written to disk and what is the potential size of the file if it is written and kept?

My concerns are for utilization and how we will need to account for or adjust for this change. I like the robustness of the change so this is mostly a question/request for how to best use the change.

**Comment by dschaper** [comment]
> uses the information in the journal to restore the database to its state prior to the start of the incomplete transaction

Will it then attempt to continue the database upgrade?

**Comment by yubiuser** [comment]
> Is the transaction file written to disk 

>  The rollback journal is always located in the same directory as the database file and has the same name as the database file except with the 8 characters "-journal" appended. The rollback journal is usually created when a transaction is first started and is usually deleted when a transaction commits or rolls back.

https://www.sqlite.org/tempfiles.html#rollback_journals

**Comment by DL6ER** [comment]
> Is the transaction file written to disk and what is the potential size of the file if it is written and kept?

Yes, it is proportional to the size of the chance so a few KB at most.

> Will it then attempt to continue the database upgrade?

Yes, FTL will try again to upgrade the database on its next start

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
