### PR TITLE
Use case-insensitive matching for env variables

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

See title. This PR follows an internal discussion and gives us some version of FTL to play around with. I am still not convinced this is something that should be done, hence, draft pull request for now.

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by yubiuser** [comment]
I'm not sure we should have this, but I can see how this is preventing CAPS_tYpos. Just a thought: does FTL log a warning if it detects an env variable that starts with `FTLCONF_` but could not be mapped to an config key?

**Comment by DL6ER** [comment]
> Just a thought: does FTL log a warning if it detects an env variable that starts with `FTLCONF_` but could not be mapped to an config key?

No. This needs extra code because we first need to iterate over the entire environment and store any `FTLCONF_` in a list. Then we have settings processing marking every parsed variable as used. In the end, we can then check if our list of env vars contains something that has not been marked as processed and issue warnings for those. Definitely worthwhile having I'd say. But I'll first wait what the fate of this PR will be and then either add it here or in a separate PR. Merge conflicts are unavoidable with this PR and another one being open at the same time.

**Comment by DL6ER** [comment]
@yubiuser https://github.com/pi-hole/FTL/pull/1719

**Comment by DL6ER** [comment]
Closing this PR. I don't think we should support case-insensitive variables.

**Pull request closed without merging**
