### PR TITLE
Add pre-compiled ARMv4, ARMv5 and ARMv8 binaries to CI workflow

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Add additional

- ARMv4 (`armv4t`, 3-stage pipeline, Thumb, ARMv4 first to drop legacy ARM 26-bit addressing),
- ARMv5 (`armv5te`, Thumb, enhanced DSP instructions, caches), and
- ARMv8 (`armv8-a`, fundamental change to the ARM architecture with mandatory vector floating point and SIMD (Neon)) 

workflows.

- ARMv6 (with hard-float, for Raspberry Pi Model 1 and Zero), and
- ARMv7 (with hard-float, for Raspberry Pi Model 2)

already exist and have just been renamed to clarify the supported architecture.

### CODE REVIEW

**Comment by DL6ER** [comment]
@pi-hole/api-approvers We need to overwrite CircleCI tests on this one as it is still expecting the old build names. If you scroll down, you can see that all the new builds are :heavy_check_mark:

**Comment by dschaper** [comment]
Updated `development` branch to only require the `build` step of CI. It will fail if any of the associated steps fail so no need to have every binary checked for merge.

**Review by dschaper — APPROVED** [review]

**Comment by Conan179** [comment]
Is there a guide on how I can compile it myself?

**Comment by yubiuser** [comment]
https://docs.pi-hole.net/ftldns/compile/

**Comment by Conan179** [comment]
OK, what do I have to do now?

**Pull request merged**
