### PR TITLE
Fix CPU utilization calculation on 32 bit systems

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Following [a report on Discourse](https://discourse.pi-hole.net/t/calc-cpu-usage-failed-in-ftl-log/66617), we change how FTL computes its own CPU utilization. The issue is that our current method of using the system-provided function `clock()` can easily overflow on 32bit systems, leading to a permanent failure after little more than two days. This has not been discovered during development as all our machines are 64 bit and the CI tests intentionally running on 32 bit obviously finished quicker than those two-and-a-half days.

This PR changes the way we measure CPU utilization to use resource details obtained from the kernel to compute a ten seconds average of FTL's CPU utilization based on the consumed CPU time (not ticks), instead. This is a very reliable metric and more in-line with what `top` and friends calculate for the processes.

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
Mhh.. I watched it a while and FTL consumed ~1-2% CPU according to htop, but the web interface reports much lower

Screenshot at 2023-12-04 20-44-55

**Comment by yubiuser** [comment]
>  compute a ten minute average

I think you meant "ten seconds average" in the PR description

**Comment by DL6ER** [comment]
Strange, this is the exact same way (`h`)`top` do it, e.g.

https://github.com/mmalecki/procps/blob/fe4c4a7314f32907b9f558ad0d8b8d0ff1cc76be/top.c#L1046-L1050

Could you do one experiment maybe for verification? Note down the shown CPU time of the entire FTL process (2.05 seconds in your screenshot) and wait 60 seconds. Then note down the value shown now (say, 4.50 seconds), subtract them and divide them by the time you waited, e.g.

```
4.5 - 2.05
---------- = 0.040 = 4.0%
    60
```

and see if this number better matches with the averaged CPU load shown by FTL. It will be hard (basically impossible) to the the exact same numbers due to different time averages but you should get at least the same order of magnitude.

Your screenshot already highlights that there is some strange inconsistency in how `htop` computes the numbers as 2% for one thread is already larger than the 1.3% for the entire process (including all its threads)...

**Comment by yubiuser** [comment]
The last commit fixed the discrepancy for me. Both `htop` and `FTL` report similar (+/- 0.1%) usage. Also calculation as you said results in almost the same values.

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
