### PR TITLE
Add error reporting during webserver initialization

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

There can be multiple causes why the embedded CivetWeb server cannot start. Pi-hole will work nonetheless but the web interface will - quite obviously - not be available. Typically, the reason for this is the absence of the webroot (`/var/www/html` - or custom configured path) or a ports configuration error. So far, FTL has only printed a very generic error message. This PR adds better error reporting in case the webserver fails to start.

Example (broken by asking `FTL` to bind to the already taken SSH port):
```
2023-10-13 19:56:34.361 [1603008M] ERR: Start of webserver failed!. Web interface will not be available!
2023-10-13 19:56:34.361 [1603008M] ERR:        Error: Failed to setup server ports (error code 10.0)
2023-10-13 19:56:34.361 [1603008M] ERR:        Hint: Check webroot /var/www/html and listening ports 80,[::]:80,443s,[::]:443s,22
```

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by yubiuser** [comment]
Maybe you picked not the best example, but we have those information already in `/var/log/pihole/webserver.log`

```
[2023-10-13 20:32:24.768 64402] Initializing HTTP server on port 80,[::]:80,443s,[::]:443s,22
[2023-10-13 20:32:24.769 64402] cannot bind to 22: 98 (Address in use)
[2023-10-13 20:32:24.769 64402] Failed to setup server ports

```

Why duplicate to `FTL.log`?

**Comment by DL6ER** [comment]
The errors provided by the library during initialization (what is new here and will be logged into `FTL.log`) are high-level errors, the ones logged to `webserver.log` are low-level errors which may not always be easy to understand for non-insiders. My feeling is that both have their own justification.

Maybe we should add a further line into `FTL.log` to also check for errors in `webserver.log` ?

**Comment by yubiuser** [comment]
Ok. This is a good addition

> Maybe we should add a further line into FTL.log to also check for errors in webserver.log ?

**Review by yubiuser — COMMENTED** [review]
It now says

```
2023-10-13 21:32:00.608 [66615M] ERR: Start of webserver failed!. Web interface will not be available!
2023-10-13 21:32:00.608 [66615M] ERR:        Error: Failed to setup server ports (error code 10.0)
2023-10-13 21:32:00.608 [66615M] ERR:        Hint: Check webroot "/var/www/html", listening ports "22,80,[::]:80,443s,[::]:443s", and see the webserver log /var/log/pihole/webserver.log
```

Independent of the error, you use a hard-coded `Hint: Check webroot \"%s\", listening ports \"%s\",` which might be totally unrelated to the error. I would suggest to only hint checking the  webserver.log

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
