### PR TITLE
Keep FTL database open

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Reopening the FTL database may lead to rare race-collisions in SQLite3. We avoid them by keeping the database connection open all the time.

### CODE REVIEW

**Comment by DL6ER** [comment]
Confirmed working in #900

**Comment by DL6ER** [comment]
CodeFactor can be ignored on this one as well. The mentioned security issue `Possible OS Command Injection (CWE-78)` isn't a problem here as the argument to `popen()` is a constant hard-coded string like `ip neigh show`. Hard to sneak something malicious into this...

**Comment by ampfinger** [comment]
I dont know if you can but could you rebuild with latest changes?
Currently for raspberry it tells me branch not found. I think it is because latest build failed.
Thanks

**Comment by DL6ER** [comment]
The failed build is without consequence and due to changes in the development branch building environment. All binaries are still up and running. However, some of them have been renamed (for the sake of clarity) so they might not be found. Can you please post the exact output?

**Comment by yubiuser** [comment]
```
sha1sum: WARNING: 1 computed checksum did NOT match
  [✗] Downloading and Installing FTL
  Error: Download of https://ftl.pi-hole.net/fix/persistent_FTL_database/pihole-FTL-aarch64-linux-gnu failed (checksum error)
  [✗] FTL Engine not installed
```

**Comment by ampfinger** [comment]
` [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              Branch is not available.
                        Use pihole checkout ftl [branchname] to switch to a valid branch.
  [i] Warning: You are using FTL from a custom branch (fix/persistent_FTL_database) and might be missing future releases.
`

**Comment by DL6ER** [comment]
@ampfinger Can you please also run
```
pihole -v
```
? If you're already on latest development (or a branch based on it), this is expected because I need to update this branch.

@yubiuser The upload might have failed before, I'll have to invent a check for this. I let the CI rebuild the aarch64 binary, could you try once more please?

**Comment by ampfinger** [comment]
Pi-hole version is development v5.0-232-gde02bcc (Latest: v5.1.2)
  AdminLTE version is devel v5.1.1-93-ge84bfa9b (Latest: v5.1.1)
  FTL version is development vDev-f69dab5 (Latest: v5.2)

Now I wanted back to this branch but cant go back

**Comment by yubiuser** [comment]
Updated worked fine now.

**Comment by ChurchOfNoise** [comment]
> 
> 
> ` [i] FTL: Branch is not available. Use pihole checkout ftl [branchname] to switch to a valid branch. [i] Warning: You are using FTL from a custom branch (fix/persistent_FTL_database) and might be missing future releases.`

I face the same thing. Just tried pihole -up again and th result remains the same.

(Output of pihole -v:"`  Pi-hole version is development v5.0-603-gde02bcc (Latest: v5.1.2)
  AdminLTE version is devel v5.1.1-127-ge84bfa9 (Latest: v5.1.1)
  FTL version is fix/persistent_FTL_database vDev-036031e (Latest: v5.2)`_

**Comment by yubiuser** [comment]
Try checking it out the branch again

`pihole checkout ftl fix/persistent_FTL_database`

**Comment by ampfinger** [comment]
> Try checking it out the branch again
> 
> `pihole checkout ftl fix/persistent_FTL_database`

Nope not working - keep telling "branch not available"

**Comment by DL6ER** [comment]
I'll update the branch when I'm back home (I'm about 6 hrs from now). I cannot do it (reliably) from my phone.

**Comment by ChurchOfNoise** [comment]
> 
> 
> > Try checking it out the branch again
> > `pihole checkout ftl fix/persistent_FTL_database`
> 
> Nope not working - keep telling "branch not available"

Dito

**Comment by ChurchOfNoise** [comment]
> 
> 
> I'll update the branch when I'm back home (I'm about 6 hrs from now). I cannot do it (reliably) from my phone.

Thanks!

**Comment by DL6ER** [comment]
Got later than expected. First thing I did was updating this branch, now I will cook dinner :-)

**Comment by ampfinger** [comment]
> Got later than expected. First thing I did was updating this branch, now I will cook dinner :-)

Thanks, checkout is working again! Enjoy your meal :)

**Comment by ChurchOfNoise** [comment]
> 
> 
> Got later than expected. First thing I did was updating this branch, now I will cook dinner :-)

Thanks!
Do you think this is ready to be merged into development?

**Comment by DL6ER** [comment]
>  Do you think this is ready to be merged into development?

Yes. Hence it is not a draft PR any more and tagged with `PR: Approval required`, hoping to pick up the attention of another developer, soon. There are other PRs waiting to be merged into `development` as well. They will come whenever they are approved.

**Review by dschaper — APPROVED** [review]

**Pull request merged**
