### PR TITLE
Added support for compilation on MIPS platform

### PR DESCRIPTION
**Pull request by abesnier**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 3 (I looked only at what was required to pass the build on mips).

---

Compiling FTL on MIPS platform would fail with the following error (repeated multiple times).
```
/path/to/FTL/src/database/../shmem.h:57:41: error: expected declaration specifiers or ‘...’ before numeric constant
   57 | ASSERT_SIZEOF(countersStruct, 240, 240, 240);
```
This error originates from `static_assert.h`, where there are no definition of `ASSERT_SIZEOF` and `STATIC_ASSERT` for the mips architecture.
This PR does not constitute a support for MIPS, only an assistance for people who want to build FTL on MIPS, and do not want to track down the compilation error.
Support added in this PR, as per [DL6ER recommendation](https://github.com/pi-hole/FTL/issues/290#issuecomment-1066162813).

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by yubiuser** [comment]
Thanks for your PR. Pi-hole requires all commits to be signed-off, otherwiese DCO will fail.
https://docs.pi-hole.net/guides/github/how-to-signoff/

**Comment by abesnier** [comment]
Sorry, I missed that. I simplified the modification and signed off the new commit. Is it ok, or do you prefer to have a full new PR?

**Comment by yubiuser** [comment]
Amending the PR is fine. It's now signed-off, but the GPG signature is missing now ...

**Review by yubiuser — DISMISSED** [review]

**Review by yubiuser — APPROVED** [review]

**Review by DL6ER — APPROVED** [review]

**Comment by DL6ER** [comment]
@abesnier Could you [sign your commits](https://docs.github.com/articles/about-gpg/)?

**Pull request merged**
