### PR TITLE
Minor integrated docs changes

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

Make HTTPS scheme the default case, change the default port from 8080 to 80 for the HTTP case, and make docs index page a Lua page to allow loading of the favicon

Screenshot from 2023-10-15 12-54-53
Screenshot from 2023-10-15 12-55-00

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Review by yubiuser — COMMENTED** [review]
https://github.com/pi-hole/FTL/blob/c5067b3a6063b0d3caf274ce25e7cf2b966b289b/src/api/docs/CMakeLists.txt#L12

**Review by yubiuser — DISMISSED** [review]

**Comment by rdwebdesign** [comment]
I have some design suggestions to use on this page, but feel free to merge the PR if you think it's not important.

**Review by yubiuser — DISMISSED** [review]

**Comment by yubiuser** [comment]
Small visual glitch: alignment
Screenshot at 2023-10-16 08-45-41

**Comment by yubiuser** [comment]
Screenshot_20231016-084657

**Comment by rdwebdesign** [comment]
> Small visual glitch: alignment

I didn't change that.
I think this is a glitch with the rapidoc itself: https://rapidocweb.com/examples/example100.html

**Comment by yubiuser** [comment]
Yeah, it's in there as well. This is only minor and could be ignored. But the authentication header should be fixed.

**Comment by rdwebdesign** [comment]
This issue is also happening on the current `development-v6` branch.

It's possible to fix it (on the browser devtools) adding `position: relative` to the CSS of the element `<div part="section-endpoint-body-expanded" class="endpoint-body get ">`, but I have no idea where this should be changed on the code. I need to search a little.

I will look for a solution later.

**Comment by rdwebdesign** [comment]
@yubiuser 

This is also a rapidoc issue. Open this link on a mobile device: https://rapidocweb.com/examples/example100.html#post-/pet/-petId-/uploadImage

**Comment by yubiuser** [comment]
We could send patches upstream, however, development on that repo looks a bit lagging.

**Comment by rdwebdesign** [comment]
We can wait for the upstream fix, or fix it ourselves in another PR, but this is another issue. 

I'm approving this PR. In my opinion, it is doing its job.

**Review by rdwebdesign — APPROVED** [review]

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
