### PR TITLE
Improvements to overall database handling

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

Some general improvements to client statement handling. We're seen a few reports where FTL crashed due to incomplete client statements. This PR addresses this. Furthermore, it adds debugging information for the SQLite3 library to make crash reports from within the `sqlite3` library less cryptic in the future.

### CODE REVIEW

**Comment by DL6ER** [comment]
This PR turned into a complete revamping of the long-term database implementation. It brings two years of adding features piece-by-piece to a uniform implementation, especially concerning error handling when the database is locked externally.

**Comment by DL6ER** [comment]
Fixes #714

**Comment by DL6ER** [comment]
Resolved merge conflict

**Comment by pralor** [comment]
This pull request has been mentioned on **Pi-hole Userspace**. There might be relevant details there:

https://discourse.pi-hole.net/t/cant-blacklist-domain/29862/6

**Pull request merged**
