### PR TITLE
Add X.509 parsing capabilities

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

This PR adds two new CLI options
```
pihole-FTL --read-x509 [certfile] [domain]
pihole-FTL --read-x509-key [certfile] [domain]
```
which can be used to parse (and hereby check) the TLS/SSL certificate to be used with Pi-hole. The first function return only public information and, hence, can be shared with others (e.g. inside a `pihole -d` run) which the second command will also print the private key so should be used only internally.

Both `certfile` and `domain` are optional (but `domain` can only be specified if `certfile` has been specified, too). If `certfile` is omitted, FTL will try to get the path from `pihole.toml:webserver.tls.cert`. If `domain` is omitted, the check will be for `pi.hole`.

This PR also includes an internal test for if the specified webserver domain `pihole.toml:webserver.domain` is included in the certificate provided in `pihole.toml:webserver.tls.cert`. If not, we print a warning to the log and also into the Pi-hole diagnosis system.

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by yubiuser** [comment]
1) The check for `webserver.domain == certificate domain` only happens on FTL restart. Wouldn't it make sense to also warn if the `webserver.domain` is changed (e.g. via web interface).
2) Should we really use a certificate for a non-matching domain

```
2023-11-09 22:00:19.295 [506292M] WARNING: SSL/TLS certificate /etc/pihole/tls.pem does not match domain test.lan!
2023-11-09 22:00:19.314 [506292M] INFO: Using SSL/TLS certificate file /etc/pihole/tls.pem

```

3) A non-match triggered a crash after startup.

```

023-11-09 22:00:19.292 [506292M] INFO: FTL is running as user pihole (UID 999)
2023-11-09 22:00:19.295 [506292M] WARNING: SSL/TLS certificate /etc/pihole/tls.pem does not match domain test.lan!
2023-11-09 22:00:19.314 [506292M] INFO: Using SSL/TLS certificate file /etc/pihole/tls.pem
2023-11-09 22:00:19.324 [506292M] INFO: Restored 1 API session from the database
2023-11-09 22:00:19.343 [506292M] INFO: Blocking status is enabled
2023-11-09 22:00:19.407 [506292/T506293] INFO: Compiled 0 allow and 1 deny regex for 2 clients in 12.2 msec
2023-11-09 22:01:16.841 [506292/T506303] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-11-09 22:01:16.842 [506292/T506303] INFO: ---------------------------->  FTL crashed!  <----------------------------
2023-11-09 22:01:16.842 [506292/T506303] INFO: !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
2023-11-09 22:01:16.842 [506292/T506303] INFO: Please report a bug at https://github.com/pi-hole/FTL/issues
2023-11-09 22:01:16.842 [506292/T506303] INFO: and include in your report already the following details:
2023-11-09 22:01:16.843 [506292/T506303] INFO: FTL has been running for 58 seconds
2023-11-09 22:01:16.843 [506292/T506303] INFO: FTL branch: new/check_certificate
2023-11-09 22:01:16.843 [506292/T506303] INFO: FTL version: vDev-d310f8e
2023-11-09 22:01:16.843 [506292/T506303] INFO: FTL commit: d310f8ef
2023-11-09 22:01:16.843 [506292/T506303] INFO: FTL date: 2023-11-09 17:50:07 +0100
2023-11-09 22:01:16.844 [506292/T506303] INFO: FTL user: started as pihole, ended as pihole
2023-11-09 22:01:16.844 [506292/T506303] INFO: Compiled for linux/arm64/v8 (compiled on CI) using cc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924
2023-11-09 22:01:16.844 [506292/T506303] INFO: Process details: MID: 506292
2023-11-09 22:01:16.844 [506292/T506303] INFO:                  PID: 506292
2023-11-09 22:01:16.844 [506292/T506303] INFO:                  TID: 506303
2023-11-09 22:01:16.844 [506292/T506303] INFO:                  Name: civetweb-worker
2023-11-09 22:01:16.845 [506292/T506303] INFO: Received signal: Segmentation fault
2023-11-09 22:01:16.845 [506292/T506303] INFO:      at address: 0
2023-11-09 22:01:16.845 [506292/T506303] INFO:      with code:  SEGV_MAPERR (Address not mapped to object)
2023-11-09 22:01:16.845 [506292/T506303] INFO: !!! INFO: pihole-FTL has not been compiled with glibc/backtrace support, not generating one !!!
2023-11-09 22:01:16.846 [506292/T506303] INFO: ------ Listing content of directory /dev/shm ------
2023-11-09 22:01:16.846 [506292/T506303] INFO: File Mode User:Group      Size  Filename
2023-11-09 22:01:16.847 [506292/T506303] INFO: rwxrwxrwx root:root       280  .
2023-11-09 22:01:16.847 [506292/T506303] INFO: rwxr-xr-x root:root         3K  ..
2023-11-09 22:01:16.848 [506292/T506303] INFO: rw------- pihole:pihole   544K  FTL-fifo-log
2023-11-09 22:01:16.848 [506292/T506303] INFO: rw------- pihole:pihole     4K  FTL-per-client-regex
2023-11-09 22:01:16.849 [506292/T506303] INFO: rw------- pihole:pihole    12K  FTL-dns-cache
2023-11-09 22:01:16.850 [506292/T506303] INFO: rw------- pihole:pihole     8K  FTL-overTime
2023-11-09 22:01:16.850 [506292/T506303] INFO: rw------- pihole:pihole   262K  FTL-queries
2023-11-09 22:01:16.851 [506292/T506303] INFO: rw------- pihole:pihole    20K  FTL-upstreams
2023-11-09 22:01:16.851 [506292/T506303] INFO: rw------- pihole:pihole    86K  FTL-clients
2023-11-09 22:01:16.852 [506292/T506303] INFO: rw------- pihole:pihole    12K  FTL-domains
2023-11-09 22:01:16.852 [506292/T506303] INFO: rw------- pihole:pihole    82K  FTL-strings
2023-11-09 22:01:16.853 [506292/T506303] INFO: rw------- pihole:pihole    16  FTL-settings
2023-11-09 22:01:16.854 [506292/T506303] INFO: rw------- pihole:pihole   292  FTL-counters
2023-11-09 22:01:16.854 [506292/T506303] INFO: rw------- pihole:pihole    88  FTL-lock
2023-11-09 22:01:16.855 [506292/T506303] INFO: ---------------------------------------------------
2023-11-09 22:01:16.855 [506292/T506303] INFO: Please also include some lines from above the !!!!!!!!! header.
2023-11-09 22:01:16.855 [506292/T506303] INFO: Thank you for helping us to improve our FTL engine!
2023-11-09 22:01:16.856 [506292/T506303] INFO: Waiting for threads to join
2023-11-09 22:01:16.856 [506292/T506303] INFO: Thread database (0) is idle, terminating it.
2023-11-09 22:01:16.857 [506292/T506303] INFO: Thread housekeeper (1) is idle, terminating it.
2023-11-09 22:01:16.858 [506292/T506303] INFO: Thread DNS client (2) is idle, terminating it.
2023-11-09 22:01:16.859 [506292/T506303] INFO: All threads joined
2023-11-09 22:01:17.874 [506292/T506303] ERR: SQL error in backup_db_sessions(): database is locked (5)

```

**Comment by yubiuser** [comment]
It happens when I try to access the diagnosis screen.

```
[New LWP 506473]
__syscall_cp_asm () at src/thread/aarch64/syscall_cp.s:28
28	src/thread/aarch64/syscall_cp.s: Datei oder Verzeichnis nicht gefunden.
(gdb) continue
Continuing.

Thread 13 "civetweb-worker" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 506471]
0x000000000075324c in strlen (s=<optimized out>, s@entry=0x0) at src/string/strlen.c:17
17	src/string/strlen.c: Datei oder Verzeichnis nicht gefunden.
(gdb) backtrace
#0  0x000000000075324c in strlen (s=<optimized out>, s@entry=0x0) at src/string/strlen.c:17
#1  0x0000000000436938 in escape_html (string=string@entry=0x0) at /app/src/webserver/http-common.c:528
#2  0x000000000047d768 in format_certificate_domain_mismatch (html=html@entry=0xffff8ff61c28 "", 
    sizeof_html=sizeof_html@entry=2048, certfile=certfile@entry=0xffff8fea9548 "/etc/pihole/tls.pem", 
    domain=domain@entry=0x0, sizeof_plain=1024, 
    plain=0xffff8ff61828 "SSL/TLS certificate /etc/pihole/tls.pem does not match domain (null)!")
    at /app/src/database/message-table.c:671
#3  0x000000000047e000 in format_certificate_domain_mismatch (domain=0x0, certfile=0xffff8fea9548 "/etc/pihole/tls.pem", 
    sizeof_html=2048, html=0xffff8ff61c28 "", sizeof_plain=1024, 
    plain=0xffff8ff61828 "SSL/TLS certificate /etc/pihole/tls.pem does not match domain (null)!")
    at /app/src/database/message-table.c:667
#4  format_messages (array=array@entry=0xffff902fd5f0) at /app/src/database/message-table.c:911
#5  0x0000000000429ffc in api_info_messages_GET (api=0xffff8ff62520) at /app/src/api/info.c:853
#6  api_info_messages (api=0xffff8ff62520) at /app/src/api/info.c:955
#7  0x000000000041f890 in api_handler (conn=0xffff9044b660, ignored=<optimized out>) at /app/src/api/api.c:195
#8  0x000000000044fc84 in handle_request (conn=conn@entry=0xffff9044b660) at /app/src/webserver/civetweb/civetweb.c:15090
#9  0x0000000000452500 in handle_request_stat_log (conn=0xffff9044b660) at /app/src/webserver/civetweb/civetweb.c:6620
#10 process_new_connection (conn=conn@entry=0xffff9044b660) at /app/src/webserver/civetweb/civetweb.c:19538
#11 0x0000000000453844 in worker_thread_run (conn=0xffff9044b660) at /app/src/webserver/civetweb/civetweb.c:19877
#12 worker_thread (thread_func_param=0xffff9044b660) at /app/src/webserver/civetweb/civetweb.c:20006
#13 0x0000000000754b2c in start (p=0xffff8ff67b00) at src/thread/pthread_create.c:207
#14 0x000000000075da94 in __clone () at src/thread/aarch64/clone.s:28
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

Thread 2 "database" received signal SIG33, Real-time event 33.
[Switching to LWP 506460]
__syscall_cp_asm () at src/thread/aarch64/syscall_cp.s:28
28	src/thread/aarch64/syscall_cp.s: Datei oder Verzeichnis nicht gefunden.
(gdb) backtrace
#0  __syscall_cp_asm () at src/thread/aarch64/syscall_cp.s:28
#1  0x0000000000753ee4 in __syscall_cp_c (nr=72, u=<optimized out>, v=<optimized out>, w=<optimized out>, 
    x=<optimized out>, y=<optimized out>, z=<optimized out>) at src/thread/pthread_cancel.c:33
#2  0x000000000074cb9c in select (n=n@entry=0, rfds=rfds@entry=0x0, wfds=wfds@entry=0x0, efds=efds@entry=0x0, 
    tv=tv@entry=0xffff90131a10) at src/select/select.c:42
#3  0x00000000006514ac in FTLselect (nfds=nfds@entry=0, readfds=readfds@entry=0x0, writefds=writefds@entry=0x0, 
    exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0xffff90131a10, file=file@entry=0x76ae48 "/app/src/timers.c", 
    func=func@entry=0x76aef0 <__FUNCTION__.0> "sleepms", line=line@entry=65) at /app/src/syscalls/select.c:25
#4  0x000000000041d9e8 in sleepms (milliseconds=milliseconds@entry=100) at /app/src/timers.c:65
#5  0x000000000041d7ec in thread_sleepms (thread=DB, milliseconds=milliseconds@entry=100) at /app/src/signals.c:380
#6  0x0000000000476944 in DB_thread (val=<optimized out>) at /app/src/database/database-thread.c:194
#7  0x0000000000754b2c in start (p=0xffff90131b00) at src/thread/pthread_create.c:207
#8  0x000000000075da94 in __clone () at src/thread/aarch64/clone.s:28
Thread 3 "housekeeper" received signal SIG33, Real-time event 33.
[Switching to LWP 506461]
__syscall_cp_asm () at src/thread/aarch64/syscall_cp.s:28
28	in src/thread/aarch64/syscall_cp.s
(gdb) backtrace
#0  __syscall_cp_asm () at src/thread/aarch64/syscall_cp.s:28
#1  0x0000000000753ee4 in __syscall_cp_c (nr=72, u=<optimized out>, v=<optimized out>, w=<optimized out>, 
    x=<optimized out>, y=<optimized out>, z=<optimized out>) at src/thread/pthread_cancel.c:33
#2  0x000000000074cb9c in select (n=n@entry=0, rfds=rfds@entry=0x0, wfds=wfds@entry=0x0, efds=efds@entry=0x0, 
    tv=tv@entry=0xffff9010e9d0) at src/select/select.c:42
#3  0x00000000006514ac in FTLselect (nfds=nfds@entry=0, readfds=readfds@entry=0x0, writefds=writefds@entry=0x0, 
    exceptfds=exceptfds@entry=0x0, timeout=timeout@entry=0xffff9010e9d0, file=file@entry=0x76ae48 "/app/src/timers.c", 
    func=func@entry=0x76aef0 <__FUNCTION__.0> "sleepms", line=line@entry=65) at /app/src/syscalls/select.c:25
#4  0x000000000041d9e8 in sleepms (milliseconds=milliseconds@entry=1000) at /app/src/timers.c:65
#5  0x000000000041d7ec in thread_sleepms (thread=thread@entry=GC, milliseconds=milliseconds@entry=1000)
    at /app/src/signals.c:380
#6  0x0000000000410644 in GC_thread (val=<optimized out>) at /app/src/gc.c:381
#7  0x0000000000754b2c in start (p=0xffff9010eb00) at src/thread/pthread_create.c:207
#8  0x000000000075da94 in __clone () at src/thread/aarch64/clone.s:28

```

**Comment by yubiuser** [comment]
```
nanopi@nanopi:~$ pihole-FTL sqlite3 /etc/pihole/pihole-FTL.db "Select * from message;"
3|1699564245|CERTIFICATE_DOMAIN_MISMATCH|/etc/pihole/tls.pem|||||
```

**Comment by DL6ER** [comment]
As always - thank you very much for your thorough reviews. It always makes me wonder how you can get so many more crashes that I get during testing but that's a good thing! Concerning your points:

> 1. The check for `webserver.domain == certificate` domain only happens on FTL restart. Wouldn't it make sense to also warn if the `webserver.domain` is changed (e.g. via web interface).

Yes, in theory. However, users may also replace the certificate file itself at any point but FTL will only read it into memory once during start. What I want to say is that the user may change the domain *and* the file so it matches again but it actually doesn't (because FTL does not update the certificate until restart).

> 2. Should we really use a certificate for a non-matching domain

Why not? It should still work with any major browser, you'd just get a warning telling you that something isn't quite right here.  See my example below (my configured `domain` is `pi.hole` as is the one-and-only valid domain for the used certificate):

Screenshot from 2023-11-10 20-58-30

where the certificate is actually not meant to be used with `ryzen`:

Screenshot from 2023-11-10 20-58-38

after accepting the warning, you will be able to use the web interface securely (encrypted)

> 3. A non-match triggered a crash after startup.

This is fascinating (see the introduction to my comment). I indeed forgot to add a definition on that the `domain` needs to be stored in the database. I also made the `escape_html()` routine more robust to avoid such crashes from ever happening again.

**Review by yubiuser — APPROVED** [review]
Side note: Do we really want to hard code issue and expiring date? Should the issued date be far in the past? Wouldn't it be better to issue on the date the certificate was really created, and give it 30 years validity from there?

Screenshot at 2023-11-10 22-01-37

**Comment by DL6ER** [comment]
> Wouldn't it be better to issue on the date the certificate was really created, and give it 30 years validity from there?

Yes, this would make sense. I think I skipped over the current creation date in case the local clock is has nothing to do with reality. However, thinking about this seems to suggest that the clock will rather be in the past than in the future so, yeah, that's actually fine. Another PR.

**Pull request merged**
