### PR TITLE
Bump sqlite to 3.20.1

### PR DESCRIPTION
**Pull request by JamieMagee**
**By submitting this pull request, I confirm the following (please check boxes, eg [X]) _Failure to fill the template will close your PR_:**

***Please submit all pull requests against the `development` branch. Failure to do so will delay or deny your request***

- [x] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [x] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [x] I have considered, and confirmed that this submission will be valuable to others.
- [x] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [x] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

3

---

Bump sqlite from `3.20.0`, to `3.20.1`. Release notes can be found [here](https://www.sqlite.org/releaselog/3_20_1.html).

_This template was created based on the work of [`udemy-dl`](https://github.com/nishad/udemy-dl/blob/master/LICENSE)._

### CODE REVIEW

**Comment by DL6ER** [comment]
Thank you for your submission. We haven't considered this update so far, as the only change,

> Fix a potential memory leak in the new sqlite3_result_pointer() interface. Ticket 7486aa54b968e9b5.

is within a routine we are not even using. We run an extensive set of (internal, undocumented) tests to ensure that an update of SQLite doesn't have negative effects on existing databases. I know that the maintainers run tests themselves but we want to be sure. We haven't undertaken this effort for this update yet, as we haven't seen any value in it. I really don't know if we will do it or not, but I'd say it is rather unlikely.

**Comment by JamieMagee** [comment]
Regarding your internal unit/integration tests, is it possible to make those public? I think that more tests could only help new contributors.

As for the change, I believe that it is a small, low risk change, but in the end it's your call.

**Comment by DL6ER** [comment]
I see your point but the reason for why the procedure is not public is mainly that it is not standardized. What we try to do is to break the database implementation "using all means". See also [Fuzz testing](https://en.wikipedia.org/wiki/Fuzzing), although we do not do it in quite an elegant (automated) fashion.

SQLite 3.21 is (slowly) on its way and should be release in the near future (http://www.sqlite.org/src/timeline?n=100&r=branch-3.21). I am inclined to wait until we can make a bigger update as the currently proposed update does not seem to bring any advantage for our users.

**Comment by JamieMagee** [comment]
I would argue that it is entirely unnecessary to perform your own fuzz testing on a dependency that you don't own.  Also because [SQLite performs fuzz testing](https://www.sqlite.org/testing.html#sql_fuzz_using_the_american_fuzzy_lop_fuzzer) as part of their standard test procedure, I imagine that they already cover a larger surface area than any custom fuzz testing.

**Comment by PromoFaux** [comment]
Closing as we will be waiting for at least 3.21 before updating sqlite

**Pull request closed without merging**
