### PR TITLE
Always return full overTime data

### PR DESCRIPTION
**Pull request by DL6ER**
**By submitting this pull request, I confirm the following:**

- [X] I have read and understood the [contributors guide](https://github.com/pi-hole/pi-hole/blob/master/CONTRIBUTING.md).
- [X] I have checked that [another pull request](https://github.com/pi-hole/FTL/pulls) for this purpose does not exist.
- [X] I have considered, and confirmed that this submission will be valuable to others.
- [X] I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
- [X] I give this submission freely, and claim no ownership to its content.

**How familiar are you with the codebase?:** 

## 10

---

The current version of FTL tries to be clever when returning overtime data and returns *trimmed* content, i.e., if there is nothing before 9am and nothing after 11am, it returns only thee two hours of data instead of a full 24 hours window. While looking at what caused https://github.com/pi-hole/FTL/issues/1335, I realized that this may be too much hand-holding and may actually even be confusing because it starts from super-wide bars (new installed and newly Initialized FTL database) progressing slowly to the well-known narrow bars after 24 hours.

This PR removes the "smart" reduction of the reported time span and ensures we always return all overtime data when requested. Even when it is partially empty, e.g. after a new install (or with a fresh database):

Screenshot from 2022-05-20 22-50-40

Another, indeed connected, change introduced in this PR is to run the garbage collection - recomputing and adjusting statistics - at the same interval as the overtime interval length. This makes the algorithms a bit simpler to understand and even saves some memory (we had to store 25 hours of data before, now we are really only storing 24 hours). All this should be invisible inside the Pi-hole world, however, when grabbing the data and displaying it in some tool that isn't aware of this, you'll see the statistics adjustment every 10 minutes now (instead of only once per hour). This is expected and correct.

Fixes https://github.com/pi-hole/FTL/issues/1335

### CODE REVIEW

**Comment by yubiuser** [comment]
I do like the idea a lot. However, it does not fix https://github.com/pi-hole/FTL/issues/1335 (completely) for me. It still stops to send data at the 10 min "border".

Bildschirmfoto zu 2022-05-01 17-13-17

(See it's already 17:13)

**Comment by yubiuser** [comment]
The current state of the PR does fix issue 1335 for me.

**Review by yubiuser — APPROVED** [review]
The scope/behavior of this PR has changed during it's development. Please adjust the PR introduction text.

**Comment by yubiuser** [comment]
No, this should not happen. It might not be related to this issue. Please enable `DEBUG_OVERTIME` (https://docs.pi-hole.net/ftldns/configfile/#debug_overtime) and see what is logged before/after a restart.

**Comment by thomasmerz** [comment]
Ok, this clarifies my question 👍🏻 You told me that my problem that I asked for in the discourse topic is (or may be?) related to this PR and issue #1312 . So should I open a new issue for this with the requested logging?

**Comment by yubiuser** [comment]
My comment above was not considering you are using docker. I thought you run bare metal with the `development` branch and still saw that log entries. So I take back what I said above and tell the opposite.
If you want to try it, there should be a docker tag `dev` which should include the development versions of all Pi-hole components.

**Comment by thomasmerz** [comment]
@yubiuser
With currently `latest` version I can't see `Found database entries in the future` anymore in any of my docker installations.
> Docker Tag [2022.07.1](https://github.com/pi-hole/docker-pi-hole/releases/2022.07.1) Pi-hole [v5.11.4](https://github.com/pi-hole/pi-hole/releases/v5.11.4) FTL [v5.16.1](https://github.com/pi-hole/FTL/releases/v5.16.1) Web Interface [v5.13](https://github.com/pi-hole/AdminLTE/releases/v5.13)

**Pull request merged**
