### PR TITLE
Implement wildcard X.509 SAN/CN (subject) domain checking

### PR DESCRIPTION
**Pull request by DL6ER**
# What does this implement/fix?

See title

Reported [on Discourse](https://discourse.pi-hole.net/t/certificate-domain-mismatch-when-using-wildcard-certificate/66544).

---

**Related issue or feature (if applicable):** N/A

**Pull request in [docs](https://github.com/pi-hole/docs) with documentation (if applicable):** N/A

---
**By submitting this pull request, I confirm the following:** 

1. I have read and understood the [contributors guide](https://docs.pi-hole.net/guides/github/contributing/), as well as this entire template. I understand which branch to base my commits and Pull Requests against. 
2. I have commented my proposed changes within the code.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [EUPL 1.2 license](https://opensource.org/licenses/EUPL-1.1)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))

## Checklist:

- [x] The code change is tested and works locally.
- [x] I based my code and PRs against the repositories `developmental` branch.
- [x] I [signed off](https://docs.pi-hole.net/guides/github/how-to-signoff/) all commits. Pi-hole enforces the [DCO](https://docs.pi-hole.net/guides/github/dco/) for all contributions
- [x] I [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) all my commits. Pi-hole requires signatures to verify authorship
- [x] I have read the above and my PR is ready for review.

### CODE REVIEW

**Comment by cscholz** [comment]
Switched to the fix branch but the message is unfortunately still the same

```
root@pi ~ $ pihole -up
  [✓] Update local cache of available packages
  [✓] Checking for git
  [✓] Checking for iproute2
  [✓] Checking for dialog
  [✓] Checking for ca-certificates

  [i] Checking for updates...
  [i] Pi-hole Core:     up to date
  [i] Web Interface:    up to date
  [i] FTL:              up to date
  [i] Warning: You are using FTL from a custom branch (fix/wildcard_crt_check) and might be missing future releases.

  [✓] Everything is up to date!
```

```
root@pi ~ $ pihole-FTL --read-x509 "/etc/nginx/ssl/domain.tld" "pi.domain.tld"
Reading certificate from /etc/nginx/ssl/domain.tld ...
Certificate does not match domain pi.domain.tld

```

**Comment by DL6ER** [comment]
Thanks for testing. One question: Is the wildcard a SAN on in the subject?
You can check with `pihole-FTL --read-x509 "/etc/nginx/ssl/domain.tld"` without a domain on the end. Or you could quote it for us and we'll check?

You can absolutely remove all possibly private content as long as the context stays intact. We also won't need tthe public key on the end of the output.

**Comment by cscholz** [comment]
> Thanks for testing. One question: Is the wildcard a SAN on in the subject? You can check with `pihole-FTL --read-x509 "/etc/nginx/ssl/domain.tld"` without a domain on the end. Or you could quote it for us and we'll check?
> 
> You can absolutely remove all possibly private content as long as the context stays intact. We also won't need tthe public key on the end of the output.

```
root@pi ~ $ pihole-FTL --read-x509 "/etc/nginx/ssl/domain.tld"
Reading certificate from /etc/nginx/ssl/domain.tld ...
Certificate (X.509):

  cert. version     : 3
  serial number     : [...]
  issuer name       : C=US, O=Let's Encrypt, CN=R3
  subject name      : CN=*.domain.tld
  issued  on        : 2023-11-13 02:40:48
  expires on        : 2024-02-11 02:40:47
  signed using      : RSA with SHA-256
  EC key size       : 256 bits
  basic constraints : CA=false
  subject alt name  :
      dNSName : *.domain.tld
      dNSName : domain.tld
  key usage         : Digital Signature
  ext key usage     : TLS Web Server Authentication, TLS Web Client Authentication
  certificate policies : ???

Public key (PEM):
-----BEGIN PUBLIC KEY-----
[...]
-----END PUBLIC KEY-----
```

**Comment by DL6ER** [comment]
I just have seen that SAN entries are not NUL-terminated strings so I had to tweak the code slightly. Furthermore, I added a check for the subject name having a wildcard possibly prefixed with `CN=` (like in your certificate).
>```
> Reading certificate from /etc/nginx/ssl/domain.tld ...
> Certificate (X.509):
>   [...]
>   subject name      : CN=*.domain.tld
>   [...]
> ```

@cscholz Would you mind re-testing this branch? You can simply rerun to `pihole checkout ftl fix/wildcard_crt_check` command to fetch the new binary once built (in about 20-30 min from now).

**Review by yubiuser — APPROVED** [review]

**Pull request merged**
